In [1]:
import os

os.listdir(".")

['.ipynb_checkpoints',
 'advocate_general_assignments.csv',
 'appeals.csv',
 'appointments.csv',
 'biographies.csv',
 'cases.csv',
 'chamber_assignments.csv',
 'citations.csv',
 'codebook.pdf',
 'decisions.csv',
 'decisions_curated.csv',
 'directory_codes.csv',
 'free_movement.csv',
 'headnotes.csv',
 'hearings.csv',
 'issues.csv',
 'iuropa_data.ipynb',
 'iuropa_data_nodes.ipynb',
 'joins.csv',
 'judges_advocates_general.csv',
 'judge_advocate_general_careers_curated.csv',
 'judge_assignments.csv',
 'keywords.csv',
 'lawyers.csv',
 'national_courts.csv',
 'observers.csv',
 'parties.csv',
 'parties_lawyers_curated.csv',
 'positions.csv',
 'positions_by_actor.csv',
 'procedures.csv',
 'proceedings.csv',
 'proceedings_curated.csv',
 'proceeding_suffixes.csv',
 'referrals.csv',
 'transfers.csv']

In [2]:
import pandas as pd
from pathlib import Path
from IPython.display import display

# Find all CSV files in the current folder
csv_files = sorted(Path(".").glob("*.csv"))

# Store DataFrames here
dfs = {}

for file in csv_files:
    name = file.stem  # e.g. "cases.csv" -> "cases"
    
    try:
        dfs[name] = pd.read_csv(file)
        
        print("=" * 100)
        print(f"{file.name} | shape: {dfs[name].shape}")
        print("=" * 100)
        
        display(dfs[name].head())
        
    except Exception as e:
        print(f"Could not read {file.name}: {e}")

====================================================================================================
advocate_general_assignments.csv | shape: (15357, 2)
====================================================================================================

                      decision_id              advocate_general_id
0  DOC_JUDG_CJ_1954_0001_19541221  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
1  DOC_JUDG_CJ_1954_0002_19541221  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
2  DOC_JUDG_CJ_1954_0003_19550211  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
3  DOC_JUDG_CJ_1954_0004_19550211  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
4  DOC_JUDG_CJ_1954_0006_19550321  ACT_EU_INST_CJEU_JUDG_AG_DE_ROE

====================================================================================================
appeals.csv | shape: (4080, 2)
====================================================================================================

  original_proceeding_id appeal_proceeding_id
0      PROC_GC_1989_0038  PROC_CJ_1990_0107_P
1      PROC_GC_1989_0040  PROC_CJ_1990_0115_P
2      PROC_GC_1989_0072  PROC_CJ_1990_0126_P
3      PROC_GC_1989_0041  PROC_CJ_1990_0132_P
4      PROC_GC_1989_0034  PROC_CJ_1990_0145_P

====================================================================================================
appointments.csv | shape: (342, 7)
====================================================================================================

,actor_id,index,court,position,is_current,start_date,end_date
0,ACT_EU_INST_CJEU_JUDG_AG_BE_RAE,1,Civil Service Tribunal,judge,False,2005-10-06,2016-08-31
1,ACT_EU_INST_CJEU_JUDG_AG_DE_KRE,1,Civil Service Tribunal,judge,False,2005-10-06,2016-04-13
2,ACT_EU_INST_CJEU_JUDG_AG_EL_TAG,1,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06
3,ACT_EU_INST_CJEU_JUDG_AG_FI_KAN,1,Civil Service Tribunal,judge,False,2005-10-06,2009-10-06
4,ACT_EU_INST_CJEU_JUDG_AG_FR_GER,1,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06

====================================================================================================
biographies.csv | shape: (3869, 7)
====================================================================================================

,actor_id,index,entry_type,description,position_type,start_year,end_year
0,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,1,position,"Titular Professor of Labour Law at Urbino, Bol...",academic,NaN,NaN
1,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,2,position,Titular Professor of Comparative Private Law a...,academic,NaN,NaN
2,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,3,membership,Member of the High Council of the Judiciary,NaN,1976.0,1981.0
3,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,4,position,Advocate General at the Court of Justice,lawyer,1982.0,1988.0
4,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,5,position,Judge at the Court of Justice,judge,1988.0,1999.0

====================================================================================================
cases.csv | shape: (49467, 5)
====================================================================================================

             case_id case_number             court prefix  year
0  CASE_CJ_1953_0001      C-1/53  Court of Justice     C-  1953
1  CASE_CJ_1953_0002      C-2/53  Court of Justice     C-  1953
2  CASE_CJ_1953_0003      C-3/53  Court of Justice     C-  1953
3  CASE_CJ_1953_0004      C-4/53  Court of Justice     C-  1953
4  CASE_CJ_1954_0001      C-1/54  Court of Justice     C-  1954

====================================================================================================
chamber_assignments.csv | shape: (25736, 3)
====================================================================================================

                      decision_id             court     chamber
0  DOC_JUDG_CJ_1954_0001_19541221  Court of Justice  Full Court
1  DOC_JUDG_CJ_1954_0002_19541221  Court of Justice  Full Court
2  DOC_JUDG_CJ_1954_0003_19550211  Court of Justice  Full Court
3  DOC_JUDG_CJ_1954_0004_19550211  Court of Justice  Full Court
4  DOC_JUDG_CJ_1954_0006_19550321  Court of Justice  Full Court

====================================================================================================
citations.csv | shape: (283994, 2)
====================================================================================================

                 citing_decision_id                 cited_decision_id
0  DOC_JUDG_CJ_1998_0082_P_20000525  DOC_JUDG_CJ_1995_0008_P_19980528
1  DOC_JUDG_CJ_1998_0082_P_20000525    DOC_JUDG_CJ_1983_0264_19850704
2    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2017_0308_20181115
3    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2016_0249_20170615
4    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2016_0560_20180307

====================================================================================================
decisions.csv | shape: (56951, 7)
====================================================================================================

,decision_id,decision_date,decision_type,court,lead_proceeding_id,ecli,celex
0,DEC_AG_VIEW_CJ_2004_0027_20040519,2004-05-19,AG view,Court of Justice,PROC_CJ_2004_0027,ECLI:EU:C:2004:313,62004CP0027
1,DEC_AG_VIEW_CJ_2008_0066_20080428,2008-04-28,AG view,Court of Justice,PROC_CJ_2008_0066,ECLI:EU:C:2008:253,62008CP0066
2,DEC_AG_VIEW_CJ_2008_0127_20080611,2008-06-11,AG view,Court of Justice,PROC_CJ_2008_0127,ECLI:EU:C:2008:335,62008CP0127
3,DEC_AG_VIEW_CJ_2008_0195_PPU_20080701,2008-07-01,AG view,Court of Justice,PROC_CJ_2008_0195_PPU,ECLI:EU:C:2008:377,62008CP0195
4,DEC_AG_VIEW_CJ_2008_0296_PPU_20080806,2008-08-06,AG view,Court of Justice,PROC_CJ_2008_0296_PPU,ECLI:EU:C:2008:455,62008CP0296

====================================================================================================
decisions_curated.csv | shape: (56951, 12)
====================================================================================================

,decision_id,ecli,celex,decision_type,decision_date,court,case_id,case_number,proceeding_id,proceeding_number,proceeding_suffix,proceeding_name
0,DEC_AG_VIEW_CJ_2004_0027_20040519,ECLI:EU:C:2004:313,62004CP0027,AG view,2004-05-19,Court of Justice,CASE_CJ_2004_0027,C-27/04,PROC_CJ_2004_0027,C-27/04,NaN,Commission of the European Communities v Counc...
1,DEC_AG_VIEW_CJ_2008_0066_20080428,ECLI:EU:C:2008:253,62008CP0066,AG view,2008-04-28,Court of Justice,CASE_CJ_2008_0066,C-66/08,PROC_CJ_2008_0066,C-66/08,NaN,Kozłowski
2,DEC_AG_VIEW_CJ_2008_0127_20080611,ECLI:EU:C:2008:335,62008CP0127,AG view,2008-06-11,Court of Justice,CASE_CJ_2008_0127,C-127/08,PROC_CJ_2008_0127,C-127/08,NaN,Blaise Baheten Metock and Others v Minister fo...
3,DEC_AG_VIEW_CJ_2008_0195_PPU_20080701,ECLI:EU:C:2008:377,62008CP0195,AG view,2008-07-01,Court of Justice,CASE_CJ_2008_0195,C-195/08,PROC_CJ_2008_0195_PPU,C-195/08 PPU,PPU,Inga Rinau
4,DEC_AG_VIEW_CJ_2008_0296_PPU_20080806,ECLI:EU:C:2008:455,62008CP0296,AG view,2008-08-06,Court of Justice,CASE_CJ_2008_0296,C-296/08,PROC_CJ_2008_0296_PPU,C-296/08 PPU,PPU,Ignacio Pedro Santesteban Goicoechea

====================================================================================================
directory_codes.csv | shape: (51955, 8)
====================================================================================================

,decision_id,code,section_code,section_label,major_code,major_label,minor_code,minor_label
0,DOC_JUDG_CJ_1954_0001_19541221,C-04.02,C,European Coal and Steel Community,C-04,Legal proceedings,C-04.02,Actions for annulment
1,DOC_JUDG_CJ_1954_0001_19541221,C-08.02,C,European Coal and Steel Community,C-08,Prices,C-08.02,Publication of prices
2,DOC_JUDG_CJ_1954_0002_19541221,C-04.02,C,European Coal and Steel Community,C-04,Legal proceedings,C-04.02,Actions for annulment
3,DOC_JUDG_CJ_1954_0002_19541221,C-08.02,C,European Coal and Steel Community,C-08,Prices,C-08.02,Publication of prices
4,DOC_JUDG_CJ_1954_0002_19541221,C-14,C,European Coal and Steel Community,C-14,General and final provisions,NaN,NaN

====================================================================================================
free_movement.csv | shape: (3454, 30)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,goods,services,persons,applicant_legal_person,applicant_economically_active,...,proportionality_test,discrimination_or_restriction,measure_rejected,protection_individual,measure_proportionate_outcome,derived_rights,incompatibility_eu_measure_primary,incompatibility_eu_measure_secondary,incompatibility_national_measure_primary,incompatibility_national_measure_secondary
0,1,DEC_C_1960_0009_J_19610714,ECLI:EU:C:1961:18:19610714,ECLI:EU:C:1961:18,61960CJ0009,1,NaN,0,1.0,NaN,...,0,0.0,-1,NaN,-1,NaN,0.0,0.0,0.0,0.0
1,2,DEC_C_1961_0007_J_19611219,ECLI:EU:C:1961:31:19611219,ECLI:EU:C:1961:31,61961CJ0007,1,NaN,0,0.0,NaN,...,0,0.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
2,3,DEC_C_1961_0010_J_19620227,ECLI:EU:C:1962:2:19620227,ECLI:EU:C:1962:2,61961CJ0010,1,NaN,0,0.0,NaN,...,0,0.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
3,4,DEC_C_1962_0002_J_19621214,ECLI:EU:C:1962:45:19621214,ECLI:EU:C:1962:45,61962CJ0002,1,NaN,0,0.0,NaN,...,0,1.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
4,5,DEC_C_1962_0016_J_19621214,ECLI:EU:C:1962:47:19621214,ECLI:EU:C:1962:47,61962CJ0016,1,NaN,0,1.0,NaN,...,0,0.0,-1,NaN,-1,NaN,0.0,0.0,0.0,0.0

====================================================================================================
headnotes.csv | shape: (118753, 2)
====================================================================================================

,decision_id,headnote
0,DOC_JUDG_CJ_2007_0004_20240704,Remuneration not forming part of a taxable tra...
1,DOC_JUDG_CJ_2007_0004_20240704,Supply of services for consideration
2,DOC_JUDG_CJ_2007_0004_20240704,Taxable transactions
3,DOC_JUDG_CJ_2007_0004_20240704,Directive 2006/112/EC
4,DOC_JUDG_CJ_2007_0004_20240704,Value added tax (VAT)

====================================================================================================
hearings.csv | shape: (22215, 2)
====================================================================================================

                      decision_id hearing_date
0  DOC_JUDG_CJ_1969_0040_19700218   1970-01-29
1  DOC_JUDG_CJ_1969_0040_19700218   1970-01-15
2  DOC_JUDG_CJ_1969_0047_19700625   1970-04-21
3  DOC_JUDG_CJ_1969_0047_19700625   1970-03-10
4  DOC_JUDG_CJ_1971_0038_19720126   1971-11-23

====================================================================================================
issues.csv | shape: (5333, 17)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,legal_issue_order,is_split,is_merged,about_derogation,about_direct_effect,about_validity,list_legal_acts,national_law_primary,national_law_secondary,list_claiming_inadmissibility
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,0,0,no,no,no,directive,none,none,none
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,2,Should any importance be attached to the fact ...,2,0,0,no,no,no,directive,none,none,none
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,3,"a) Is it significant, as far as the applicatio...",3a_b_c,0,1,no,no,no,directive,none,none,none
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,4,Is the wording used in Article 13B(d) points 3...,4,0,0,no,no,no,directive,none,none,none
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,5,"In interpreting Article 13B(d) points 3 to 5, ...",5,0,0,no,no,no,directive,none,none,none

====================================================================================================
joins.csv | shape: (6882, 2)
====================================================================================================

  joined_proceeding_id lead_proceeding_id
0    PROC_CJ_1954_0009  PROC_CJ_1954_0007
1    PROC_CJ_1954_0010  PROC_CJ_1954_0008
2    PROC_CJ_1957_0003  PROC_CJ_1956_0007
3    PROC_CJ_1957_0004  PROC_CJ_1956_0007
4    PROC_CJ_1957_0005  PROC_CJ_1956_0007

====================================================================================================
judge_advocate_general_careers_curated.csv | shape: (342, 19)
====================================================================================================

,actor_id,display_label,display_label_ascii,full_name,first_name,last_name,member_state,birth_year,is_female,court,position,is_current,start_date,end_date,was_judge,was_academic,was_civil_servant,was_lawyer,was_politician
0,ACT_EU_INST_CJEU_JUDG_AG_BE_RAE,Van Raepenbusch,Van Raepenbusch,Sean Van Raepenbusch,Sean,Van Raepenbusch,Belgium,1956,0,Civil Service Tribunal,judge,False,2005-10-06,2016-08-31,0,1,1,1,0
1,ACT_EU_INST_CJEU_JUDG_AG_DE_KRE,Kreppel,Kreppel,Horstpeter Kreppel,Horstpeter,Kreppel,Germany,1945,0,Civil Service Tribunal,judge,False,2005-10-06,2016-04-13,1,1,1,1,0
2,ACT_EU_INST_CJEU_JUDG_AG_EL_TAG,Tagaras,Tagaras,Haris Tagaras,Haris,Tagaras,Greece,1955,0,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06,0,1,1,1,0
3,ACT_EU_INST_CJEU_JUDG_AG_FI_KAN,Kanninen,Kanninen,Heikki Kanninen,Heikki,Kanninen,Finland,1952,0,Civil Service Tribunal,judge,False,2005-10-06,2009-10-06,1,1,1,1,0
4,ACT_EU_INST_CJEU_JUDG_AG_FR_GER,Gervasoni,Gervasoni,Stéphane Gervasoni,Stéphane,Gervasoni,France,1967,0,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06,1,1,1,1,0

====================================================================================================
judge_assignments.csv | shape: (119036, 3)
====================================================================================================

,decision_id,judge_id,is_judge_rapporteur
0,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_BE_DEL,False
1,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_DE_RIE,True
2,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_FR_REU,False
3,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_IT_PIL,False
4,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_LU_HAM,False

====================================================================================================
judges_advocates_general.csv | shape: (278, 9)
====================================================================================================

,actor_id,display_label,display_label_ascii,full_name,first_name,last_name,member_state,birth_year,is_female
0,ACT_EU_INST_CJEU_JUDG_AG_DE_ALB,Alber,Alber,Siegbert Alber,Siegbert,Alber,Germany,1936,0
1,ACT_EU_INST_CJEU_JUDG_AG_BG_ARA,Arabadjiev,Arabadjiev,Alexander Arabadjiev,Alexander,Arabadjiev,Bulgaria,1949,0
2,ACT_EU_INST_CJEU_JUDG_AG_ES_ARA_SAH,Arastey Sahún,Arastey Sahun,Maria Lourdes Arastey Sahún,Maria Lourdes,Arastey Sahún,Spain,1959,1
3,ACT_EU_INST_CJEU_JUDG_AG_CY_ARE,Arestis,Arestis,George Arestis,George,Arestis,Cyprus,1945,0
4,ACT_EU_INST_CJEU_JUDG_AG_AT_AZI,Azizi,Azizi,Josef Azizi,Josef,Azizi,Austria,1948,0

====================================================================================================
keywords.csv | shape: (58859, 2)
====================================================================================================

                      decision_id       keyword
0  DOC_JUDG_CJ_1954_0001_19541221  ECSC matters
1  DOC_JUDG_CJ_1954_0001_19541221        Prices
2  DOC_JUDG_CJ_1954_0002_19541221  ECSC matters
3  DOC_JUDG_CJ_1954_0002_19541221        Prices
4  DOC_JUDG_CJ_1954_0003_19550211  ECSC matters

====================================================================================================
lawyers.csv | shape: (217008, 6)
====================================================================================================

,decision_id,index,lawyer_id,lawyer_name,client_id,client_name
0,DOC_JUDG_CJ_1954_0001_19541221,1,ACT_LAW_[reuter],Reuter,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE
1,DOC_JUDG_CJ_1954_0001_19541221,3,ACT_LAW_[coutard],Coutard,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
2,DOC_JUDG_CJ_1954_0001_19541221,2,ACT_LAW_[gaudet],Gaudet,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
3,DOC_JUDG_CJ_1954_0002_19541221,4,ACT_LAW_[coutard],Coutard,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
4,DOC_JUDG_CJ_1954_0002_19541221,3,ACT_LAW_[catalano],Catalano,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...

====================================================================================================
national_courts.csv | shape: (1566, 13)
====================================================================================================

,key_id,iuropa_national_court_id,national_court,iuropa_member_state_id,member_state,court_location,english_translation,in_hierarchy,court_level,court_prestige,court_collegiality,court_competence,court_competence_detailed
0,1,NAT_COURT_AT_ASW,Arbeits- und Sozialgericht Wien,ACT_EU_MS_AT,Austria,Vienna,Labor and Social Court,1,lower court,not applicable,panel,specialized,labor law; social law
1,2,NAT_COURT_AT_A,Asylgerichtshof,ACT_EU_MS_AT,Austria,Vienna,Asylum Court,1,higher court,not applicable,panel,specialized,immigration law
2,3,NAT_COURT_AT_BS_1_REG_LIN_FD_OBE,Berufungssenat I der Region Linz bei der Finan...,ACT_EU_MS_AT,Austria,Linz,Appeals Senate I of the Linz Region at the Sta...,0,not applicable,lower court,panel,specialized,tax law
3,4,NAT_COURT_AT_BS_5_FD_WIE_NIE_BUR,Berufungssenat V der Finanzlandesdirektion für...,ACT_EU_MS_AT,Austria,Vienna,Appeals Senate V of the State Financial Direct...,0,not applicable,lower court,panel,specialized,tax law
4,5,NAT_COURT_AT_BG_BLE,Bezirksgericht Bleiburg,ACT_EU_MS_AT,Austria,Bleiburg,District Court of Bleiburg,1,lower court,not applicable,single judge,general,not applicable

====================================================================================================
observers.csv | shape: (38783, 5)
====================================================================================================

,decision_id,index,observer_id,observer_name,observer_type
0,DOC_JUDG_CJ_1962_0028_19630327,1,ACT_COMP_[societe-da-costa-en-schaake-n-v],société Da Costa en Schaake N. V.,company
1,DOC_JUDG_CJ_1962_0028_19630327,2,ACT_COMP_[societe-jacob-meijer-n-v],société Jacob Meijer N. V.,company
2,DOC_JUDG_CJ_1962_0028_19630327,3,ACT_COMP_[societe-hoechst-holland-n-v],société Hoechst-Holland N. V.,company
3,DOC_JUDG_CJ_1962_0028_19630327,4,ACT_NAT_INST_[administration-fiscale-neerlanda...,administration fiscale néerlandaise,national institution
4,DOC_JUDG_CJ_1963_0073_19640218,1,ACT_COMP_[n-v-internationale-crediet-en-handel...,N. V. Internationale Crediet-en Handelsverenig...,company

====================================================================================================
parties.csv | shape: (129629, 6)
====================================================================================================

,decision_id,index,party_id,party_name,party_type,party_role
0,DOC_JUDG_CJ_1954_0001_19541221,1,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE,EU member state,applicant
1,DOC_JUDG_CJ_1954_0001_19541221,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant
2,DOC_JUDG_CJ_1954_0002_19541221,1,ACT_EU_MS_IT,GOUVERNEMENT DE LA RÉPUBLIQUE ITALIENNE,EU member state,applicant
3,DOC_JUDG_CJ_1954_0002_19541221,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant
4,DOC_JUDG_CJ_1954_0003_19550211,1,ACT_ORG_[associazione-industrie-siderurgiche-i...,ASSOCIAZIONE INDUSTRIE SIDERURGICHE ITALIANE,organization,applicant

====================================================================================================
parties_lawyers_curated.csv | shape: (129629, 12)
====================================================================================================

,decision_id,decision_date,court,proceeding_id,proceeding_name,party_index,party_id,party_name,party_type,party_role,lawyer_count,lawyer_name_list
0,DOC_JUDG_CJ_1954_0001_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0001,France v ECSC High Authority,1,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE,EU member state,applicant,1,Reuter
1,DOC_JUDG_CJ_1954_0001_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0001,France v ECSC High Authority,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant,2,Coutard; Gaudet
2,DOC_JUDG_CJ_1954_0002_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0002,Italian Republic v High Authority of the Europ...,1,ACT_EU_MS_IT,GOUVERNEMENT DE LA RÉPUBLIQUE ITALIENNE,EU member state,applicant,2,Arias; Monaco
3,DOC_JUDG_CJ_1954_0002_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0002,Italian Republic v High Authority of the Europ...,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant,2,Coutard; Catalano
4,DOC_JUDG_CJ_1954_0003_19550211,1955-02-11,Court of Justice,PROC_CJ_1954_0003,Assider v ECSC High Authority,1,ACT_ORG_[associazione-industrie-siderurgiche-i...,ASSOCIAZIONE INDUSTRIE SIDERURGICHE ITALIANE,organization,applicant,2,Grassetti; Rebua

====================================================================================================
positions.csv | shape: (18617, 14)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,position_id,position,for_national_court,national_autonomy,individual_rights,list_actors_primary,list_actors_secondary
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,Yes and no,no,would restrict autonomy,not applicable,Advocate General; applicant; Court of Justice ...,none
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,2,No and no,no,would not restrict autonomy,not applicable,defendant,none
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,3,No,no,would not restrict autonomy,not applicable,European Commission,none
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,4,some of the operations are covered by the exem...,no,competing effect on autonomy,not applicable,United Kingdom,none
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,2,Should any importance be attached to the fact ...,5,Yes,no,uncertain,not applicable,applicant,none

====================================================================================================
positions_by_actor.csv | shape: (41595, 15)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,position_id,position_type,position,for_national_court,national_autonomy,individual_rights,iuropa_actor_id,actor
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,none,Advocate General
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,none,applicant
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,ACT_EU_INST_CJEU,Court of Justice of the European Union (CJEU)
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,2,primary,No and no,no,would not restrict autonomy,not applicable,none,defendant
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,3,primary,No,no,would not restrict autonomy,not applicable,ACT_EU_INST_COM,European Commission

====================================================================================================
procedures.csv | shape: (30261, 4)
====================================================================================================

                      decision_id  index             procedure     outcome
0  DOC_JUDG_CJ_1954_0001_19541221      1  action for annulment   unfounded
1  DOC_JUDG_CJ_1954_0001_19541221      2  action for annulment  successful
2  DOC_JUDG_CJ_1954_0002_19541221      1  action for annulment   unfounded
3  DOC_JUDG_CJ_1954_0002_19541221      2  action for annulment  successful
4  DOC_JUDG_CJ_1954_0003_19550211      1  action for annulment   unfounded

====================================================================================================
proceeding_suffixes.csv | shape: (59, 2)
====================================================================================================

  proceeding_suffix                                        description
0                AJ                       an application for legal aid
1            AJ-REC  an application for the rectification of a deci...
2            AJ-REV  an application for the revision of a decision ...
3               DEP                         an application as to costs
4              DISS  an application for the separation of joined cases

====================================================================================================
proceedings.csv | shape: (52785, 8)
====================================================================================================

,proceeding_id,case_id,proceeding_number,court,prefix,year,suffix,proceeding_name
0,PROC_CJ_1953_0001,CASE_CJ_1953_0001,C-1/53,Court of Justice,C-,1953,NaN,Verband Deutscher Reeder v ECSC High Authority
1,PROC_CJ_1953_0002,CASE_CJ_1953_0002,C-2/53,Court of Justice,C-,1953,NaN,Bunkerfirmen-Vereinigung v ECSC High Authority
2,PROC_CJ_1953_0003,CASE_CJ_1953_0003,C-3/53,Court of Justice,C-,1953,NaN,France v ECSC High Authority
3,PROC_CJ_1953_0004,CASE_CJ_1953_0004,C-4/53,Court of Justice,C-,1953,NaN,Belgium v ECSC High Authority
4,PROC_CJ_1954_0001,CASE_CJ_1954_0001,C-1/54,Court of Justice,C-,1954,NaN,France v ECSC High Authority

====================================================================================================
proceedings_curated.csv | shape: (52785, 20)
====================================================================================================

,proceeding_id,case_id,court,year,proceeding_suffix,proceeding_name,is_main_proceeding,joined_proceeding_count,joined_proceeding_list,lead_proceeding_id,is_transferred,transferred_to_proceeding_id,appeal_count,appeal_list,is_appeal_of,appeal_of_list,decision_count,decision_list,has_judgment,has_ag_opinion
0,PROC_CJ_1953_0001,CASE_CJ_1953_0001,Court of Justice,1953,NaN,Verband Deutscher Reeder v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0001_19540507,0,0
1,PROC_CJ_1953_0002,CASE_CJ_1953_0002,Court of Justice,1953,NaN,Bunkerfirmen-Vereinigung v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0002_19540507,0,0
2,PROC_CJ_1953_0003,CASE_CJ_1953_0003,Court of Justice,1953,NaN,France v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0003_19531105,0,0
3,PROC_CJ_1953_0004,CASE_CJ_1953_0004,Court of Justice,1953,NaN,Belgium v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0004_19531030,0,0
4,PROC_CJ_1954_0001,CASE_CJ_1954_0001,Court of Justice,1954,NaN,France v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,2,DOC_JUDG_CJ_1954_0001_19541221; DOC_OPIN_CJ_19...,1,1

====================================================================================================
referrals.csv | shape: (9269, 7)
====================================================================================================

,decision_id,index,national_court_id,national_court_name,member_state,date_referred,date_received
0,DOC_JUDG_CJ_1961_0013_19620406,1,ACT_NAT_CT_[cour-appel-haye-deuxieme-chambre],"cour d'appel de La Haye, deuxième chambre",Netherlands,1961-06-20,NaN
1,DOC_JUDG_CJ_1962_0026_19630205,1,ACT_NAT_CT_[tariefcommissie-tribunal-administr...,"Tariefcommissie, tribunal administratif néerla...",Netherlands,NaN,NaN
2,DOC_JUDG_CJ_1962_0028_19630327,1,ACT_NAT_CT_[tariefcommissie-tribunal-administr...,"Tariefcommissie, tribunal administratif néerla...",Netherlands,NaN,NaN
3,DOC_JUDG_CJ_1963_0073_19640218,1,ACT_NAT_CT_[tribunal-administratif-economique-...,Tribunal administratif économique de droit née...,Netherlands,NaN,NaN
4,DOC_JUDG_CJ_1963_0075_19640319,1,ACT_NAT_CT_[raad-van-beroep],Raad van Beroep,Netherlands,NaN,NaN

====================================================================================================
transfers.csv | shape: (894, 2)
====================================================================================================

  original_proceeding_id  new_proceeding_id
0      PROC_CJ_1986_0179  PROC_GC_1989_0001
1      PROC_CJ_1986_0186  PROC_GC_1989_0002
2      PROC_CJ_1986_0189  PROC_GC_1989_0003
3      PROC_CJ_1986_0192  PROC_GC_1989_0004
4      PROC_CJ_1986_0194  PROC_GC_1989_0005

# Build IUROPA judgment-level node features

This section constructs a **one-row-per-judgment** node table for later relational event modelling (REM) and exports it as `node_features.xlsx`.

Design principles:

- The node universe is IUROPA **judgments** (`decision_type == "judgment"`) across all courts by default.
- Time-varying features (age, CJEU tenure, prior assignments, professional experience, novelty) are evaluated **as of the judgment date** and never use later observations.
- One-to-many IUROPA tables are aggregated before merging so that the result remains one row per `decision_id`.
- Network-history variables such as indegree, PageRank, citation momentum, etc. are deliberately **not** included here.
- The workbook contains the node table plus a feature dictionary and missingness summary.

You can restrict the universe later (for example, `Court of Justice` only) by changing the configuration below.

In [3]:
# ============================================================
# CONFIGURATION + INPUT CHECKS
# ============================================================

import numpy as np
import pandas as pd
import re
from collections import defaultdict
from functools import lru_cache
from pathlib import Path

# Default REM node universe: all judgments in IUROPA.
# Example restriction: COURTS = {"Court of Justice"}
COURTS = None
NODE_DECISION_TYPES = {"judgment"}

# Metadata-based novelty uses only earlier judgments.
# Set False if you want a faster first run.
RUN_NOVELTY = True

OUTPUT_XLSX = Path("node_features.xlsx")

required_core = {
    "decisions",
    "proceedings",
    "procedures",
    "judge_assignments",
    "advocate_general_assignments",
    "judges_advocates_general",
    "appointments",
}

missing_core = sorted(required_core - set(dfs))
if missing_core:
    raise FileNotFoundError(
        "Missing core IUROPA tables: " + ", ".join(missing_core)
        + ". Put the CSVs in the same folder as this notebook and rerun the import cell above."
    )

optional_tables = [
    "decisions_curated", "proceedings_curated", "cases", "hearings", "referrals",
    "joins", "appeals", "transfers", "chamber_assignments", "biographies",
    "judge_advocate_general_careers_curated", "directory_codes", "keywords",
    "headnotes", "parties", "observers", "national_courts"
]

print("Core tables available.")
print("Optional tables available:")
for t in optional_tables:
    print(f"  {t:45s} {'YES' if t in dfs else 'NO'}")

Core tables available.
Optional tables available:
  decisions_curated                             YES
  proceedings_curated                           YES
  cases                                         YES
  hearings                                      YES
  referrals                                     YES
  joins                                         YES
  appeals                                       YES
  transfers                                     YES
  chamber_assignments                           YES
  biographies                                   YES
  judge_advocate_general_careers_curated        YES
  directory_codes                               YES
  keywords                                      YES
  headnotes                                     YES
  parties                                       YES
  observers                                     YES
  national_courts                               YES

In [4]:
# ============================================================
# HELPERS
# ============================================================

def slugify(x):
    """Safe, stable column-name fragment."""
    x = str(x).strip().lower()
    x = re.sub(r"[^a-z0-9]+", "_", x)
    return x.strip("_") or "missing"


def unique_join(series, sep="; "):
    vals = [str(x).strip() for x in series.dropna() if str(x).strip()]
    return sep.join(sorted(set(vals))) if vals else np.nan


def n_unique_nonmissing(series):
    return series.dropna().nunique()


def bool_any(series):
    s = pd.to_numeric(series, errors="coerce").fillna(0)
    return int((s != 0).any())


def first_nonmissing(series):
    s = series.dropna()
    return s.iloc[0] if len(s) else np.nan


def excel_safe_value(x):
    """Excel cells cannot contain strings longer than 32,767 characters."""
    if isinstance(x, str) and len(x) > 32760:
        return x[:32757] + "..."
    return x


def merge_one_to_one(left, right, on="decision_id", how="left"):
    """Merge and assert that the node table remains one row per decision."""
    before = len(left)
    out = left.merge(right, on=on, how=how)
    if len(out) != before:
        raise ValueError(
            f"Merge on {on!r} changed row count from {before:,} to {len(out):,}. "
            "Aggregate the right-hand table first."
        )
    return out


def add_count_pivots(df, index, col, prefix):
    """Return wide count dummies such as party_type__company_count."""
    if col not in df.columns or df.empty:
        return pd.DataFrame({index: df[index].drop_duplicates()})
    tmp = df.dropna(subset=[index, col]).copy()
    if tmp.empty:
        return pd.DataFrame(columns=[index])
    p = pd.crosstab(tmp[index], tmp[col])
    p.columns = [f"{prefix}__{slugify(c)}_count" for c in p.columns]
    return p.reset_index()


def prior_count_by_actor_date(df, actor_col, date_col, out_col):
    """
    Number of earlier rows for the actor, using only dates strictly before the current date.
    Rows on the same date do not count one another.
    """
    tmp = df[[actor_col, date_col]].dropna().copy()
    daily = (
        tmp.groupby([actor_col, date_col], as_index=False)
           .size()
           .rename(columns={"size": "n_on_date"})
           .sort_values([actor_col, date_col])
    )
    daily[out_col] = daily.groupby(actor_col)["n_on_date"].cumsum() - daily["n_on_date"]
    return daily[[actor_col, date_col, out_col]]


def interval_union_days(intervals, asof_date):
    """Union length of date intervals clipped at asof_date (avoids double counting overlaps)."""
    asof = pd.Timestamp(asof_date)
    clean = []
    for start, end in intervals:
        if pd.isna(start):
            continue
        start = pd.Timestamp(start)
        if start > asof:
            continue
        end = asof if pd.isna(end) else min(pd.Timestamp(end), asof)
        if end < start:
            continue
        clean.append((start, end))
    if not clean:
        return np.nan
    clean.sort(key=lambda z: z[0])
    merged = [list(clean[0])]
    for start, end in clean[1:]:
        if start <= merged[-1][1] + pd.Timedelta(days=1):
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return sum((end - start).days + 1 for start, end in merged)


def descriptive_missingness(df):
    return (
        pd.DataFrame({
            "feature": df.columns,
            "n_missing": [df[c].isna().sum() for c in df.columns],
            "pct_missing": [100 * df[c].isna().mean() for c in df.columns],
            "n_unique": [df[c].nunique(dropna=True) for c in df.columns],
            "dtype": [str(df[c].dtype) for c in df.columns],
        })
        .sort_values(["pct_missing", "feature"], ascending=[False, True])
        .reset_index(drop=True)
    )

In [5]:
# ============================================================
# 1. BASE NODE UNIVERSE: ONE ROW PER JUDGMENT
# ============================================================

decisions = dfs["decisions"].copy()
decisions["decision_date"] = pd.to_datetime(decisions["decision_date"], errors="coerce")

nodes = decisions[
    decisions["decision_type"].astype(str).str.lower().isin({x.lower() for x in NODE_DECISION_TYPES})
].copy()

if COURTS is not None:
    nodes = nodes[nodes["court"].isin(COURTS)].copy()

nodes = nodes.drop_duplicates("decision_id").reset_index(drop=True)
nodes["decision_year"] = nodes["decision_date"].dt.year

# Use the curated decision table when available because it already links decisions -> proceedings -> cases.
if "decisions_curated" in dfs:
    dc = dfs["decisions_curated"].copy()
    keep = [c for c in [
        "decision_id", "case_id", "case_number", "proceeding_id", "proceeding_number",
        "proceeding_suffix", "proceeding_name"
    ] if c in dc.columns]
    dc = dc[keep].drop_duplicates("decision_id")
    nodes = merge_one_to_one(nodes, dc, on="decision_id")
else:
    proceedings = dfs["proceedings"].copy()
    p_keep = [c for c in [
        "proceeding_id", "case_id", "proceeding_number", "year", "suffix", "proceeding_name"
    ] if c in proceedings.columns]
    p = proceedings[p_keep].rename(columns={
        "proceeding_id": "lead_proceeding_id",
        "year": "proceeding_year",
        "suffix": "proceeding_suffix"
    })
    nodes = merge_one_to_one(nodes, p, on="lead_proceeding_id")

    if "cases" in dfs and "case_id" in nodes.columns:
        cases = dfs["cases"].copy()
        c_keep = [c for c in ["case_id", "case_number", "year"] if c in cases.columns]
        c = cases[c_keep].rename(columns={"year": "case_year"}).drop_duplicates("case_id")
        nodes = merge_one_to_one(nodes, c, on="case_id")

# Normalize the proceeding key used below.
if "proceeding_id" not in nodes.columns and "lead_proceeding_id" in nodes.columns:
    nodes["proceeding_id"] = nodes["lead_proceeding_id"]

# The year a proceeding was lodged is available in proceedings; it is not an exact filing date.
proc = dfs["proceedings"].copy()
if "year" in proc.columns:
    proc_year = proc[["proceeding_id", "year"]].drop_duplicates("proceeding_id").rename(
        columns={"year": "proceeding_lodged_year"}
    )
    nodes = merge_one_to_one(nodes, proc_year, on="proceeding_id")
    nodes["approx_years_lodging_to_decision"] = (
        nodes["decision_year"] - pd.to_numeric(nodes["proceeding_lodged_year"], errors="coerce")
    )

print(f"Judgment nodes: {len(nodes):,}")
print(nodes[[c for c in ["decision_id", "decision_date", "court", "case_number", "proceeding_name"] if c in nodes]].head())

Judgment nodes: 25,778
                      decision_id decision_date             court case_number  \
0  DOC_JUDG_CJ_1954_0001_19541221    1954-12-21  Court of Justice      C-1/54
1  DOC_JUDG_CJ_1954_0002_19541221    1954-12-21  Court of Justice      C-2/54
2  DOC_JUDG_CJ_1954_0003_19550211    1955-02-11  Court of Justice      C-3/54
3  DOC_JUDG_CJ_1954_0004_19550211    1955-02-11  Court of Justice      C-4/54
4  DOC_JUDG_CJ_1954_0006_19550321    1955-03-21  Court of Justice      C-6/54

                                     proceeding_name
0                       France v ECSC High Authority
1  Italian Republic v High Authority of the Europ...
2                      Assider v ECSC High Authority
3  Industrie Siderurgiche Associate (ISA) v High ...
4  Kingdom of the Netherlands v High Authority of...

In [6]:
# ============================================================
# 2. PROCEDURES + OUTCOMES
# ============================================================

procedures = dfs["procedures"].copy()

proc_agg = procedures.groupby("decision_id", as_index=False).agg(
    procedures=("procedure", unique_join),
    n_procedures=("procedure", n_unique_nonmissing),
    outcomes=("outcome", unique_join),
    n_outcomes=("outcome", n_unique_nonmissing),
)

nodes = merge_one_to_one(nodes, proc_agg)

# Wide procedure and outcome counts retain the full coding rather than imposing a hand-picked taxonomy.
proc_pivot = add_count_pivots(procedures, "decision_id", "procedure", "procedure")
outcome_pivot = add_count_pivots(procedures, "decision_id", "outcome", "outcome")
nodes = merge_one_to_one(nodes, proc_pivot)
nodes = merge_one_to_one(nodes, outcome_pivot)

# A few convenient high-level flags.
proc_text = nodes["procedures"].fillna("").str.lower()
nodes["is_preliminary_ruling"] = proc_text.str.contains("preliminary").astype(int)
nodes["is_appeal"] = proc_text.str.contains("appeal").astype(int)
nodes["is_annulment"] = proc_text.str.contains("annulment").astype(int)
nodes["is_infringement"] = (
    proc_text.str.contains("failure to fulfill") | proc_text.str.contains("failure to fulfil")
).astype(int)
nodes["is_damages_action"] = proc_text.str.contains("damages").astype(int)
nodes["is_failure_to_act"] = proc_text.str.contains("failure to act").astype(int)

In [7]:
# ============================================================
# 3. PROCEEDING STRUCTURE: JOINS, APPEALS, TRANSFERS
# ============================================================

# The curated proceedings table is the cleanest source when available.
if "proceedings_curated" in dfs:
    pc = dfs["proceedings_curated"].copy()
    keep = [c for c in [
        "proceeding_id", "is_main_proceeding", "joined_proceeding_count",
        "joined_proceeding_list", "is_transferred", "transferred_to_proceeding_id",
        "appeal_count", "appeal_list", "is_appeal_of", "appeal_of_list",
        "decision_count", "has_judgment", "has_ag_opinion"
    ] if c in pc.columns]
    pc = pc[keep].drop_duplicates("proceeding_id")
    nodes = merge_one_to_one(nodes, pc, on="proceeding_id")

    if "joined_proceeding_count" in nodes:
        nodes["is_joined_case"] = (pd.to_numeric(nodes["joined_proceeding_count"], errors="coerce").fillna(0) > 0).astype(int)
        nodes["n_proceedings_in_bundle"] = 1 + pd.to_numeric(nodes["joined_proceeding_count"], errors="coerce").fillna(0)
else:
    # Fallback: aggregate joins directly.
    if "joins" in dfs:
        joins = dfs["joins"].copy()
        j = joins.groupby("lead_proceeding_id", as_index=False).agg(
            joined_proceeding_count=("joined_proceeding_id", "nunique"),
            joined_proceeding_list=("joined_proceeding_id", unique_join),
        ).rename(columns={"lead_proceeding_id": "proceeding_id"})
        nodes = merge_one_to_one(nodes, j, on="proceeding_id")
        nodes["joined_proceeding_count"] = nodes["joined_proceeding_count"].fillna(0)
        nodes["is_joined_case"] = (nodes["joined_proceeding_count"] > 0).astype(int)
        nodes["n_proceedings_in_bundle"] = 1 + nodes["joined_proceeding_count"]

# Note: "appeal_count" in proceedings_curated can refer to later appeals and is therefore
# descriptive, but should NOT be used as a predictor in an ex-ante model of the original judgment.
# By contrast, "is_appeal_of" / the appeal procedure itself is already known at the judgment date.

In [8]:
# ============================================================
# 4. HEARINGS + CASE-TIMING FEATURES
# ============================================================

if "hearings" in dfs:
    hearings = dfs["hearings"].copy()
    hearings["hearing_date"] = pd.to_datetime(hearings["hearing_date"], errors="coerce")
    h = hearings.groupby("decision_id", as_index=False).agg(
        n_hearings=("hearing_date", "count"),
        first_hearing_date=("hearing_date", "min"),
        last_hearing_date=("hearing_date", "max"),
    )
    nodes = merge_one_to_one(nodes, h)
    nodes["days_first_hearing_to_decision"] = (nodes["decision_date"] - nodes["first_hearing_date"]).dt.days
    nodes["days_last_hearing_to_decision"] = (nodes["decision_date"] - nodes["last_hearing_date"]).dt.days

# Preliminary-reference timing is handled with the referral metadata below because those
# dates are exact when reported, unlike the generic proceeding year.

In [9]:
# ============================================================
# 5. CHAMBER / FORMATION
# ============================================================

if "chamber_assignments" in dfs:
    chambers = dfs["chamber_assignments"].copy()
    ch = chambers.groupby("decision_id", as_index=False).agg(
        chambers=("chamber", unique_join),
        n_chambers=("chamber", n_unique_nonmissing),
    )
    nodes = merge_one_to_one(nodes, ch)
    chamber_text = nodes["chambers"].fillna("").str.lower()
    nodes["is_grand_chamber"] = chamber_text.str.contains("grand chamber").astype(int)
    nodes["is_full_court_or_plenary"] = (
        chamber_text.str.contains("plenary") | chamber_text.str.contains("full court")
    ).astype(int)

## Judicial personnel features

The following cells construct features **at the judgment date**:

- approximate age from `birth_year`;
- exact cumulative CJEU service time from appointment intervals, clipped at the judgment date and unioned so overlapping appointments do not double count;
- prior judge / rapporteur / AG assignments using only decisions on **strictly earlier dates**;
- panel-level age, tenure, experience, gender and Member-State diversity;
- dated professional-background measures from the biography table.

The biography code is intentionally conservative: where start/end years are missing, it does not invent a duration.

In [10]:
# ============================================================
# 6. PREPARE PERSON MASTER + APPOINTMENT-HISTORY FUNCTIONS
# ============================================================

people = dfs["judges_advocates_general"].copy()
appointments = dfs["appointments"].copy()
appointments["start_date"] = pd.to_datetime(appointments["start_date"], errors="coerce")
appointments["end_date"] = pd.to_datetime(appointments["end_date"], errors="coerce")

# Store appointment records by actor for fast as-of calculations.
appointment_records = {}
for actor_id, g in appointments.groupby("actor_id"):
    appointment_records[actor_id] = g[["court", "position", "start_date", "end_date"]].to_dict("records")

@lru_cache(maxsize=None)
def _service_days_cached(actor_id, asof_date_str, court, position_key):
    asof = pd.Timestamp(asof_date_str)
    positions = None if position_key == "__ANY__" else set(position_key.split("||"))
    intervals = []
    for r in appointment_records.get(actor_id, []):
        if court != "__ANY__" and r["court"] != court:
            continue
        if positions is not None and r["position"] not in positions:
            continue
        intervals.append((r["start_date"], r["end_date"]))
    return interval_union_days(intervals, asof)


def service_years(actor_id, asof_date, court=None, positions=None):
    if pd.isna(actor_id) or pd.isna(asof_date):
        return np.nan
    court_key = "__ANY__" if court is None or pd.isna(court) else str(court)
    pos_key = "__ANY__" if positions is None else "||".join(sorted(positions))
    d = _service_days_cached(str(actor_id), pd.Timestamp(asof_date).strftime("%Y-%m-%d"), court_key, pos_key)
    return np.nan if pd.isna(d) else d / 365.25

# First CJEU appointment date is fixed historical information.
first_appointment = (
    appointments.groupby("actor_id", as_index=False)["start_date"].min()
    .rename(columns={"start_date": "first_cjeu_appointment_date"})
)

In [11]:
# ============================================================
# 7. JUDGES, RAPPORTEUR + PANEL FEATURES
# ============================================================

ja = dfs["judge_assignments"].copy()
ja = ja.merge(nodes[["decision_id", "decision_date", "court"]], on="decision_id", how="inner")
ja = ja.merge(people, left_on="judge_id", right_on="actor_id", how="left", suffixes=("", "_person"))
ja = ja.merge(first_appointment, on="actor_id", how="left")

# Age at judgment date (birth year only -> approximate age).
ja["judge_age_approx"] = ja["decision_date"].dt.year - pd.to_numeric(ja["birth_year"], errors="coerce")

# Cumulative service up to the judgment date.
JUDGE_LIKE_POSITIONS = {"judge", "President", "Vice-President"}
ja["judge_cjeu_service_years_any_role"] = ja.apply(
    lambda r: service_years(r["judge_id"], r["decision_date"]), axis=1
)
ja["judge_judicial_service_years"] = ja.apply(
    lambda r: service_years(r["judge_id"], r["decision_date"], positions=JUDGE_LIKE_POSITIONS), axis=1
)
ja["judge_current_court_judicial_service_years"] = ja.apply(
    lambda r: service_years(r["judge_id"], r["decision_date"], court=r["court"], positions=JUDGE_LIKE_POSITIONS), axis=1
)

# Experience measured as the number of earlier decision assignments.
prior_judge = prior_count_by_actor_date(ja, "judge_id", "decision_date", "prior_judge_assignments")
ja = ja.merge(prior_judge, on=["judge_id", "decision_date"], how="left")

# Prior assignments specifically as Judge-Rapporteur.
rapporteur_hist = ja[ja["is_judge_rapporteur"].astype(bool)].copy()
prior_rap = prior_count_by_actor_date(
    rapporteur_hist, "judge_id", "decision_date", "prior_rapporteur_assignments"
)
ja = ja.merge(prior_rap, on=["judge_id", "decision_date"], how="left")
ja["prior_rapporteur_assignments"] = ja["prior_rapporteur_assignments"].fillna(0)

# Panel aggregates.
panel = ja.groupby("decision_id", as_index=False).agg(
    panel_judge_ids=("judge_id", unique_join),
    panel_judge_names=("display_label", unique_join),
    panel_size=("judge_id", "nunique"),
    panel_mean_age_approx=("judge_age_approx", "mean"),
    panel_median_age_approx=("judge_age_approx", "median"),
    panel_min_age_approx=("judge_age_approx", "min"),
    panel_max_age_approx=("judge_age_approx", "max"),
    panel_age_sd=("judge_age_approx", "std"),
    panel_share_female=("is_female", "mean"),
    panel_n_member_states=("member_state", n_unique_nonmissing),
    panel_member_states=("member_state", unique_join),
    panel_mean_cjeu_service_years=("judge_cjeu_service_years_any_role", "mean"),
    panel_mean_judicial_service_years=("judge_judicial_service_years", "mean"),
    panel_mean_current_court_service_years=("judge_current_court_judicial_service_years", "mean"),
    panel_mean_prior_judge_assignments=("prior_judge_assignments", "mean"),
    panel_median_prior_judge_assignments=("prior_judge_assignments", "median"),
)
panel["panel_member_state_diversity"] = panel["panel_n_member_states"] / panel["panel_size"].replace(0, np.nan)
nodes = merge_one_to_one(nodes, panel)

# Rapporteur-specific node attributes (rare multiple rapporteurs are aggregated rather than dropped).
rap = ja[ja["is_judge_rapporteur"].astype(bool)].copy()
rap_agg = rap.groupby("decision_id", as_index=False).agg(
    rapporteur_ids=("judge_id", unique_join),
    rapporteur_names=("display_label", unique_join),
    n_rapporteurs=("judge_id", "nunique"),
    rapporteur_birth_year=("birth_year", "mean"),
    rapporteur_age_approx=("judge_age_approx", "mean"),
    rapporteur_is_female=("is_female", "mean"),
    rapporteur_member_states=("member_state", unique_join),
    rapporteur_cjeu_service_years=("judge_cjeu_service_years_any_role", "mean"),
    rapporteur_judicial_service_years=("judge_judicial_service_years", "mean"),
    rapporteur_current_court_service_years=("judge_current_court_judicial_service_years", "mean"),
    rapporteur_prior_judge_assignments=("prior_judge_assignments", "mean"),
    rapporteur_prior_rapporteur_assignments=("prior_rapporteur_assignments", "mean"),
)
nodes = merge_one_to_one(nodes, rap_agg)

print("Judge/panel features added.")

Judge/panel features added.

In [12]:
# ============================================================
# 8. ADVOCATE-GENERAL FEATURES
# ============================================================

aga = dfs["advocate_general_assignments"].copy()
aga = aga.merge(nodes[["decision_id", "decision_date", "court"]], on="decision_id", how="inner")
aga = aga.merge(people, left_on="advocate_general_id", right_on="actor_id", how="left", suffixes=("", "_person"))
aga = aga.merge(first_appointment, on="actor_id", how="left")

aga["ag_age_approx"] = aga["decision_date"].dt.year - pd.to_numeric(aga["birth_year"], errors="coerce")
aga["ag_cjeu_service_years_any_role"] = aga.apply(
    lambda r: service_years(r["advocate_general_id"], r["decision_date"]), axis=1
)
aga["ag_role_service_years"] = aga.apply(
    lambda r: service_years(r["advocate_general_id"], r["decision_date"], positions={"Advocate-General"}), axis=1
)
aga["ag_current_court_role_service_years"] = aga.apply(
    lambda r: service_years(
        r["advocate_general_id"], r["decision_date"], court=r["court"], positions={"Advocate-General"}
    ), axis=1
)

prior_ag = prior_count_by_actor_date(aga, "advocate_general_id", "decision_date", "ag_prior_assignments")
aga = aga.merge(prior_ag, on=["advocate_general_id", "decision_date"], how="left")

ag_agg = aga.groupby("decision_id", as_index=False).agg(
    ag_ids=("advocate_general_id", unique_join),
    ag_names=("display_label", unique_join),
    n_advocates_general=("advocate_general_id", "nunique"),
    ag_birth_year=("birth_year", "mean"),
    ag_age_approx=("ag_age_approx", "mean"),
    ag_is_female=("is_female", "mean"),
    ag_member_states=("member_state", unique_join),
    ag_cjeu_service_years=("ag_cjeu_service_years_any_role", "mean"),
    ag_role_service_years=("ag_role_service_years", "mean"),
    ag_current_court_role_service_years=("ag_current_court_role_service_years", "mean"),
    ag_prior_assignments=("ag_prior_assignments", "mean"),
)

nodes = merge_one_to_one(nodes, ag_agg)
nodes["has_advocate_general"] = nodes["n_advocates_general"].fillna(0).gt(0).astype(int)

print("AG features added.")

AG features added.

In [13]:
# ============================================================
# 9. DATED PROFESSIONAL BACKGROUND FOR RAPPORTEUR + AG
# ============================================================

# These measures use only biography entries with a known start year no later than the judgment.
# Duration measures use only entries with BOTH start and end years known. Missing dates are not imputed.

BIO_TYPES = ["lawyer", "civil servant", "academic", "politician", "judge", "other"]

if "biographies" in dfs:
    bios = dfs["biographies"].copy()
    bios = bios[bios["entry_type"].astype(str).str.lower().eq("position")].copy()
    bios["start_year"] = pd.to_numeric(bios["start_year"], errors="coerce")
    bios["end_year"] = pd.to_numeric(bios["end_year"], errors="coerce")

    # civil servant; lawyer is intentionally split into both categories.
    bio_rows = []
    for _, r in bios.iterrows():
        ptypes = [x.strip() for x in str(r.get("position_type", "")).split(";") if x.strip() and x != "nan"]
        for pt in ptypes:
            rr = r.copy()
            rr["position_type_split"] = pt
            bio_rows.append(rr)
    bios_long = pd.DataFrame(bio_rows) if bio_rows else pd.DataFrame()

    bio_by_actor = {aid: g.copy() for aid, g in bios_long.groupby("actor_id")} if not bios_long.empty else {}

    @lru_cache(maxsize=None)
    def bio_summary(actor_id, asof_year):
        out = {}
        g = bio_by_actor.get(actor_id)
        for pt in BIO_TYPES:
            out[f"bio_has_{slugify(pt)}_by_date"] = 0
            out[f"bio_n_{slugify(pt)}_positions_started_by_date"] = 0
            out[f"bio_known_years_{slugify(pt)}_by_date"] = 0.0
        if g is None or pd.isna(asof_year):
            return out
        y = int(asof_year)
        for pt in BIO_TYPES:
            x = g[g["position_type_split"].eq(pt)].copy()
            x_started = x[x["start_year"].notna() & (x["start_year"] <= y)]
            out[f"bio_has_{slugify(pt)}_by_date"] = int(len(x_started) > 0)
            out[f"bio_n_{slugify(pt)}_positions_started_by_date"] = int(len(x_started))

            # Conservative known-duration measure: require both endpoints.
            xd = x_started[x_started["end_year"].notna()].copy()
            if not xd.empty:
                intervals = []
                for _, rr in xd.iterrows():
                    a = int(rr["start_year"])
                    b = min(int(rr["end_year"]), y)
                    if b >= a:
                        intervals.append((a, b))
                # union integer years to avoid double counting concurrent positions of the same type
                covered = set()
                for a, b in intervals:
                    covered.update(range(a, b + 1))
                out[f"bio_known_years_{slugify(pt)}_by_date"] = float(len(covered))
        return out

    def attach_bio_features(person_rows, id_col, prefix):
        if person_rows.empty:
            return pd.DataFrame(columns=["decision_id"])
        rows = []
        for _, r in person_rows[["decision_id", id_col, "decision_date"]].drop_duplicates().iterrows():
            d = bio_summary(str(r[id_col]), r["decision_date"].year if pd.notna(r["decision_date"]) else np.nan)
            d = {f"{prefix}_{k}": v for k, v in d.items()}
            d["decision_id"] = r["decision_id"]
            rows.append(d)
        tmp = pd.DataFrame(rows)
        # Multiple AGs / rapporteurs are rare. For counts/years use mean; for flags use max.
        if tmp.empty:
            return pd.DataFrame(columns=["decision_id"])
        agg_map = {}
        for c in tmp.columns:
            if c == "decision_id":
                continue
            agg_map[c] = "max" if "_has_" in c else "mean"
        return tmp.groupby("decision_id", as_index=False).agg(agg_map)

    rap_bio = attach_bio_features(rap, "judge_id", "rapporteur")
    ag_bio = attach_bio_features(aga, "advocate_general_id", "ag")
    nodes = merge_one_to_one(nodes, rap_bio)
    nodes = merge_one_to_one(nodes, ag_bio)

    print("Dated biography features added.")
else:
    print("biographies.csv not found; biography features skipped.")

Dated biography features added.

In [14]:
# ============================================================
# 10. SUBJECT MATTER: DIRECTORY CODES, KEYWORDS, HEADNOTES
# ============================================================

if "directory_codes" in dfs:
    d = dfs["directory_codes"].copy()
    directory_agg = d.groupby("decision_id", as_index=False).agg(
        directory_codes=("code", unique_join),
        n_directory_codes=("code", n_unique_nonmissing),
        directory_sections=("section_label", unique_join),
        n_directory_sections=("section_label", n_unique_nonmissing),
        directory_major_labels=("major_label", unique_join),
        n_directory_major_labels=("major_label", n_unique_nonmissing),
        directory_minor_labels=("minor_label", unique_join),
        n_directory_minor_labels=("minor_label", n_unique_nonmissing),
    )
    nodes = merge_one_to_one(nodes, directory_agg)
    section_pivot = add_count_pivots(d, "decision_id", "section_label", "directory_section")
    nodes = merge_one_to_one(nodes, section_pivot)

if "keywords" in dfs:
    kw = dfs["keywords"].copy()
    kw_agg = kw.groupby("decision_id", as_index=False).agg(
        keywords=("keyword", unique_join),
        n_keywords=("keyword", n_unique_nonmissing),
    )
    nodes = merge_one_to_one(nodes, kw_agg)

if "headnotes" in dfs:
    hn = dfs["headnotes"].copy()
    hn_agg = hn.groupby("decision_id", as_index=False).agg(
        headnotes=("headnote", unique_join),
        n_headnotes=("headnote", "count"),
    )
    nodes = merge_one_to_one(nodes, hn_agg)

In [15]:
# ============================================================
# 11. METADATA NOVELTY USING ONLY EARLIER JUDGMENTS
# ============================================================

# Novelty here is NOT a network statistic. It compares a judgment's legal metadata with
# judgments that already existed before its decision date.
#
# For a feature-set S_i:
#   new_share      = share of i's values never observed in an earlier judgment
#   max_jaccard    = maximum Jaccard similarity to any earlier judgment
#   novelty        = 1 - max_jaccard
#
# Same-day judgments do NOT count as prior judgments.
# Directory codes have a pre-/post-Lisbon classification break; interpret exact-code novelty
# around 2009 with caution. Section/major-label novelty is provided as a more stable alternative.

def temporal_set_novelty(node_frame, feature_frame, value_col, prefix):
    base = node_frame[["decision_id", "decision_date"]].dropna(subset=["decision_date"]).copy()
    fs = (
        feature_frame.dropna(subset=["decision_id", value_col])
        .groupby("decision_id")[value_col]
        .apply(lambda s: set(str(x) for x in s.dropna()))
        .to_dict()
    )

    previous_sets = {}
    inverted = defaultdict(set)
    seen_values = set()
    results = []

    for date, day in base.sort_values("decision_date").groupby("decision_date", sort=True):
        day_results = []
        for decision_id in day["decision_id"]:
            s = fs.get(decision_id, set())
            if not s:
                day_results.append({
                    "decision_id": decision_id,
                    f"{prefix}_new_share": np.nan,
                    f"{prefix}_max_jaccard_to_prior": np.nan,
                    f"{prefix}_novelty": np.nan,
                })
                continue

            new_share = len(s - seen_values) / len(s)
            candidates = set()
            for val in s:
                candidates.update(inverted.get(val, set()))

            if candidates:
                max_j = 0.0
                for other in candidates:
                    os = previous_sets[other]
                    denom = len(s | os)
                    if denom:
                        max_j = max(max_j, len(s & os) / denom)
            else:
                max_j = 0.0

            day_results.append({
                "decision_id": decision_id,
                f"{prefix}_new_share": new_share,
                f"{prefix}_max_jaccard_to_prior": max_j,
                f"{prefix}_novelty": 1.0 - max_j,
            })

        # Only AFTER scoring the full day do today's judgments enter history.
        for decision_id in day["decision_id"]:
            s = fs.get(decision_id, set())
            if not s:
                continue
            previous_sets[decision_id] = s
            seen_values.update(s)
            for val in s:
                inverted[val].add(decision_id)

        results.extend(day_results)

    return pd.DataFrame(results)

if RUN_NOVELTY:
    if "directory_codes" in dfs:
        d = dfs["directory_codes"]
        for value_col, prefix in [
            ("code", "directory_code"),
            ("section_label", "directory_section"),
            ("major_label", "directory_major"),
        ]:
            if value_col in d.columns:
                nov = temporal_set_novelty(nodes, d, value_col, prefix)
                nodes = merge_one_to_one(nodes, nov)

    if "keywords" in dfs and "keyword" in dfs["keywords"].columns:
        nov = temporal_set_novelty(nodes, dfs["keywords"], "keyword", "keyword")
        nodes = merge_one_to_one(nodes, nov)

    print("Metadata novelty features added.")
else:
    print("RUN_NOVELTY=False; novelty calculation skipped.")

Metadata novelty features added.

In [16]:
# ============================================================
# 12. PARTIES + OBSERVERS / EX-ANTE SALIENCE PROXIES
# ============================================================

if "parties" in dfs:
    p = dfs["parties"].copy()
    party_agg = p.groupby("decision_id", as_index=False).agg(
        party_ids=("party_id", unique_join),
        party_types=("party_type", unique_join),
        party_roles=("party_role", unique_join),
        n_parties=("party_id", n_unique_nonmissing),
        n_party_types=("party_type", n_unique_nonmissing),
    )
    nodes = merge_one_to_one(nodes, party_agg)
    nodes = merge_one_to_one(nodes, add_count_pivots(p, "decision_id", "party_type", "party_type"))
    nodes = merge_one_to_one(nodes, add_count_pivots(p, "decision_id", "party_role", "party_role"))

    # Standardized party IDs make this a reasonably robust convenience flag.
    commission_party = (
        p.assign(_is_commission=p["party_id"].astype(str).str.contains("commission", case=False, na=False))
         .groupby("decision_id", as_index=False)["_is_commission"].max()
         .rename(columns={"_is_commission": "has_commission_party"})
    )
    commission_party["has_commission_party"] = commission_party["has_commission_party"].astype(int)
    nodes = merge_one_to_one(nodes, commission_party)

if "observers" in dfs:
    o = dfs["observers"].copy()
    obs_agg = o.groupby("decision_id", as_index=False).agg(
        observer_ids=("observer_id", unique_join),
        observer_types=("observer_type", unique_join),
        n_observers=("observer_id", n_unique_nonmissing),
        n_observer_types=("observer_type", n_unique_nonmissing),
    )
    nodes = merge_one_to_one(nodes, obs_agg)
    nodes = merge_one_to_one(nodes, add_count_pivots(o, "decision_id", "observer_type", "observer_type"))

    commission_obs = (
        o.assign(_is_commission=o["observer_id"].astype(str).str.contains("commission", case=False, na=False))
         .groupby("decision_id", as_index=False)["_is_commission"].max()
         .rename(columns={"_is_commission": "has_commission_observer"})
    )
    commission_obs["has_commission_observer"] = commission_obs["has_commission_observer"].astype(int)
    nodes = merge_one_to_one(nodes, commission_obs)

In [17]:
# ============================================================
# 13. REFERRALS + NATIONAL-COURT CHARACTERISTICS
# ============================================================

if "referrals" in dfs:
    r = dfs["referrals"].copy()
    r["date_referred"] = pd.to_datetime(r["date_referred"], errors="coerce")
    r["date_received"] = pd.to_datetime(r["date_received"], errors="coerce")

    # Enrich with national-court metadata when available.
    if "national_courts" in dfs:
        nc = dfs["national_courts"].copy()
        nc_key = None
        for candidate in ["national_court_id", "iuropa_national_court_id"]:
            if candidate in nc.columns:
                nc_key = candidate
                break
        if nc_key is not None and "national_court_id" in r.columns:
            nc_keep = [c for c in [
                nc_key, "court_location", "in_hierarchy", "court_level", "court_prestige",
                "court_collegiality", "court_competence", "court_competence_detailed"
            ] if c in nc.columns]
            nc2 = nc[nc_keep].drop_duplicates(nc_key).rename(columns={nc_key: "national_court_id"})
            r = r.merge(nc2, on="national_court_id", how="left")

    ref_agg_dict = {
        "national_court_id": [("referring_court_ids", unique_join), ("n_referring_courts", n_unique_nonmissing)],
        "member_state": [("referring_member_states", unique_join), ("n_referring_member_states", n_unique_nonmissing)],
        "date_referred": [("first_date_referred", "min"), ("last_date_referred", "max")],
        "date_received": [("first_date_received", "min"), ("last_date_received", "max")],
    }

    # Named aggregation assembled dynamically to tolerate version differences.
    named = {}
    for col, specs in ref_agg_dict.items():
        if col in r.columns:
            for out_name, fun in specs:
                named[out_name] = (col, fun)
    for col in ["court_level", "court_prestige", "court_collegiality", "court_competence", "court_competence_detailed"]:
        if col in r.columns:
            named[f"referring_{col}s"] = (col, unique_join)
            named[f"n_referring_{col}s"] = (col, n_unique_nonmissing)

    ref_agg = r.groupby("decision_id", as_index=False).agg(**named)
    ref_count = r.groupby("decision_id", as_index=False).size().rename(columns={"size": "n_referrals"})
    ref_agg = ref_agg.merge(ref_count, on="decision_id", how="left")
    nodes = merge_one_to_one(nodes, ref_agg)

    for col in ["court_level", "court_prestige", "court_collegiality", "court_competence"]:
        if col in r.columns:
            nodes = merge_one_to_one(nodes, add_count_pivots(r, "decision_id", col, f"referring_{col}"))

    # Exact timing for preliminary-reference cases where the judgment reports the dates.
    if "first_date_referred" in nodes:
        nodes["days_first_referral_to_decision"] = (nodes["decision_date"] - nodes["first_date_referred"]).dt.days
        nodes["days_last_referral_to_decision"] = (nodes["decision_date"] - nodes["last_date_referred"]).dt.days
    if "first_date_received" in nodes:
        nodes["days_first_receipt_to_decision"] = (nodes["decision_date"] - nodes["first_date_received"]).dt.days
        nodes["days_last_receipt_to_decision"] = (nodes["decision_date"] - nodes["last_date_received"]).dt.days

    if "first_hearing_date" in nodes and "first_date_received" in nodes:
        nodes["days_first_receipt_to_first_hearing"] = (
            nodes["first_hearing_date"] - nodes["first_date_received"]
        ).dt.days

## Features deliberately not included yet

The node workbook intentionally leaves out **endogenous citation-network history**, including indegree, PageRank, prior citation momentum, HITS scores, two-paths, etc. Those can be added later as time-varying REM covariates.

It also does not calculate semantic-text novelty because the CSV bundle shown here contains headnotes/keywords but not a full judgment-text table. If you later add the IUROPA text corpus, a clean extension is an embedding-based novelty score comparing each judgment only with earlier judgments.

In [18]:
# ============================================================
# 14. FINAL CLEANUP + SANITY CHECKS
# ============================================================

# Reassert one row per node.
if nodes["decision_id"].duplicated().any():
    dupes = nodes.loc[nodes["decision_id"].duplicated(False), "decision_id"].head(20).tolist()
    raise ValueError(f"Node table is not unique by decision_id. Examples: {dupes}")

# Put key identifiers first; leave all dynamically constructed columns afterwards.
key_cols = [c for c in [
    "decision_id", "decision_date", "decision_year", "decision_type", "court", "ecli", "celex",
    "case_id", "case_number", "proceeding_id", "lead_proceeding_id", "proceeding_number",
    "proceeding_suffix", "proceeding_name"
] if c in nodes.columns]
other_cols = [c for c in nodes.columns if c not in key_cols]
nodes = nodes[key_cols + other_cols].sort_values(["decision_date", "decision_id"]).reset_index(drop=True)

# Convert any accidental set/list objects to strings for Excel.
for c in nodes.columns:
    if nodes[c].dtype == "object":
        nodes[c] = nodes[c].map(
            lambda x: "; ".join(map(str, x)) if isinstance(x, (list, tuple, set)) else x
        )
        nodes[c] = nodes[c].map(excel_safe_value)

missingness = descriptive_missingness(nodes)

print(f"Final node table: {nodes.shape[0]:,} judgments x {nodes.shape[1]:,} features")
print(f"Unique decision IDs: {nodes['decision_id'].nunique():,}")
display(nodes.head())
display(missingness.head(30))

Final node table: 25,778 judgments x 271 features
Unique decision IDs: 25,778

,decision_id,decision_date,decision_year,decision_type,court,ecli,celex,case_id,case_number,proceeding_id,...,referring_court_competences,n_referring_court_competences,referring_court_competence_detaileds,n_referring_court_competence_detaileds,n_referrals,days_first_referral_to_decision,days_last_referral_to_decision,days_first_receipt_to_decision,days_last_receipt_to_decision,days_first_receipt_to_first_hearing
0,DOC_JUDG_CJ_1954_0001_19541221,1954-12-21,1954,judgment,Court of Justice,ECLI:EU:C:1954:7,61954CJ0001,CASE_CJ_1954_0001,C-1/54,PROC_CJ_1954_0001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DOC_JUDG_CJ_1954_0002_19541221,1954-12-21,1954,judgment,Court of Justice,ECLI:EU:C:1954:8,61954CJ0002,CASE_CJ_1954_0002,C-2/54,PROC_CJ_1954_0002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DOC_JUDG_CJ_1954_0003_19550211,1955-02-11,1955,judgment,Court of Justice,ECLI:EU:C:1955:2,61954CJ0003,CASE_CJ_1954_0003,C-3/54,PROC_CJ_1954_0003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DOC_JUDG_CJ_1954_0004_19550211,1955-02-11,1955,judgment,Court of Justice,ECLI:EU:C:1955:3,61954CJ0004,CASE_CJ_1954_0004,C-4/54,PROC_CJ_1954_0004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DOC_JUDG_CJ_1954_0006_19550321,1955-03-21,1955,judgment,Court of Justice,ECLI:EU:C:1955:5,61954CJ0006,CASE_CJ_1954_0006,C-6/54,PROC_CJ_1954_0006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,feature,n_missing,pct_missing,n_unique,dtype
0,referring_court_collegialitys,25778,100.000000,0,float64
1,referring_court_competence_detaileds,25778,100.000000,0,float64
2,referring_court_competences,25778,100.000000,0,float64
3,referring_court_levels,25778,100.000000,0,float64
4,referring_court_prestiges,25778,100.000000,0,float64
5,transferred_to_proceeding_id,25777,99.996121,1,object
6,joined_proceeding_list,23944,92.885406,1818,object
7,appeal_of_list,23904,92.730235,1842,object
8,proceeding_suffix,23632,91.675072,17,object
9,appeal_list,23054,89.432850,2700,object
10,days_first_receipt_to_first_hearing,21552,83.606176,557,float64
11,days_first_receipt_to_decision,19855,77.023043,778,float64
12,days_last_receipt_to_decision,19855,77.023043,776,float64
13,first_date_received,19855,77.023043,3473,datetime64[ns]
14,last_date_received,19855,77.023043,3468,datetime64[ns]
15,days_first_referral_to_decision,19845,76.984250,837,float64
16,days_last_referral_to_decision,19845,76.984250,835,float64
17,first_date_referred,19845,76.984250,3487,datetime64[ns]
18,last_date_referred,19845,76.984250,3479,datetime64[ns]
19,has_commission_observer,17426,67.600279,2,float64
20,n_observer_types,17426,67.600279,8,float64
21,n_observers,17426,67.600279,25,float64
22,observer_ids,17426,67.600279,7557,object
23,observer_type__company_count,17426,67.600279,17,float64
24,observer_type__consumer_organization_count,17426,67.600279,4,float64
25,observer_type__educational_organization_count,17426,67.600279,2,float64
26,observer_type__eu_institution_count,17426,67.600279,6,float64
27,observer_type__eu_member_state_count,17426,67.600279,20,float64
28,observer_type__industry_organization_count,17426,67.600279,6,float64
29,observer_type__international_organization_count,17426,67.600279,2,float64

In [19]:
# ============================================================
# 15. FEATURE DICTIONARY
# ============================================================

feature_descriptions = {
    "decision_id": "IUROPA unique decision identifier; primary node key.",
    "decision_date": "Date the judgment was published.",
    "decision_year": "Calendar year of the judgment.",
    "court": "Court issuing the judgment.",
    "case_number": "Court case number linked to the decision.",
    "proceeding_name": "Proceeding name from the Registry/curated linkage.",
    "approx_years_lodging_to_decision": "Decision year minus proceeding lodged year; approximate because IUROPA proceedings provides lodging year, not a universal exact filing date.",
    "n_hearings": "Number of recorded hearings for the decision.",
    "days_first_hearing_to_decision": "Days from first recorded hearing to judgment.",
    "days_last_hearing_to_decision": "Days from last recorded hearing to judgment.",
    "is_grand_chamber": "1 if chamber assignment contains Grand Chamber.",
    "panel_size": "Number of distinct judges assigned to the judgment.",
    "panel_mean_age_approx": "Mean approximate judge age at judgment date, using birth year.",
    "panel_mean_cjeu_service_years": "Mean cumulative CJEU service time of panel judges up to judgment date.",
    "panel_mean_prior_judge_assignments": "Mean number of strictly earlier judge assignments among panel members.",
    "rapporteur_age_approx": "Approximate age of Judge-Rapporteur at judgment date, using birth year.",
    "rapporteur_cjeu_service_years": "Cumulative CJEU service of Judge-Rapporteur up to judgment date.",
    "rapporteur_prior_judge_assignments": "Earlier judge assignments of Judge-Rapporteur before judgment date.",
    "rapporteur_prior_rapporteur_assignments": "Earlier Judge-Rapporteur assignments before judgment date.",
    "ag_age_approx": "Approximate age of assigned Advocate-General at judgment date, using birth year.",
    "ag_cjeu_service_years": "Cumulative CJEU service of assigned AG up to judgment date.",
    "ag_prior_assignments": "Earlier AG assignments before judgment date.",
    "directory_code_novelty": "1 minus maximum Jaccard overlap in exact directory codes with any strictly earlier judgment; use cautiously around the Lisbon directory break.",
    "directory_section_novelty": "1 minus maximum Jaccard overlap in directory sections with any strictly earlier judgment.",
    "keyword_novelty": "1 minus maximum Jaccard overlap in EUR-Lex keywords with any strictly earlier judgment.",
    "n_parties": "Number of unique standardized parties in the judgment.",
    "n_observers": "Number of unique written observers; applies mainly to preliminary rulings.",
    "n_referring_courts": "Number of distinct referring national courts linked to the judgment.",
    "days_first_referral_to_decision": "Days from earliest reported national referral date to judgment.",
    "days_first_receipt_to_decision": "Days from earliest reported Court receipt date to judgment.",
}


def infer_feature_group(c):
    if c.startswith("rapporteur_"):
        return "Judge-Rapporteur"
    if c.startswith("ag_") or c == "has_advocate_general":
        return "Advocate-General"
    if c.startswith("panel_"):
        return "Panel"
    if c.startswith("procedure") or c.startswith("outcome") or c.startswith("is_"):
        return "Procedure / case structure"
    if c.startswith("directory") or c.startswith("keyword") or c.startswith("headnote") or c.startswith("n_directory") or c.startswith("n_keyword") or c.startswith("n_headnote"):
        return "Subject matter / novelty"
    if c.startswith("party") or c.startswith("n_part") or c.startswith("has_commission_party"):
        return "Parties"
    if c.startswith("observer") or c.startswith("n_observer") or c.startswith("has_commission_observer"):
        return "Observers"
    if c.startswith("referring_") or "referral" in c or "receipt" in c or c.startswith("n_referr"):
        return "Referrals / national courts"
    if "hearing" in c or "lodging" in c:
        return "Timing"
    if c in key_cols:
        return "Identifiers"
    return "Other"

feature_dictionary = pd.DataFrame({
    "feature": nodes.columns,
    "group": [infer_feature_group(c) for c in nodes.columns],
    "description": [feature_descriptions.get(c, "Constructed directly from the named IUROPA field/table; see notebook cell and column prefix for definition.") for c in nodes.columns],
    "time_safe_for_ex_ante_model": [
        "NO - future information; descriptive only" if c in {"appeal_count", "appeal_list"}
        else "YES / contemporaneous or historical"
        for c in nodes.columns
    ]
})

display(feature_dictionary.head(40))

,feature,group,description,time_safe_for_ex_ante_model
0,decision_id,Identifiers,IUROPA unique decision identifier; primary nod...,YES / contemporaneous or historical
1,decision_date,Identifiers,Date the judgment was published.,YES / contemporaneous or historical
2,decision_year,Identifiers,Calendar year of the judgment.,YES / contemporaneous or historical
3,decision_type,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
4,court,Identifiers,Court issuing the judgment.,YES / contemporaneous or historical
5,ecli,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
6,celex,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
7,case_id,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
8,case_number,Identifiers,Court case number linked to the decision.,YES / contemporaneous or historical
9,proceeding_id,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
10,lead_proceeding_id,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
11,proceeding_number,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
12,proceeding_suffix,Identifiers,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
13,proceeding_name,Identifiers,Proceeding name from the Registry/curated link...,YES / contemporaneous or historical
14,proceeding_lodged_year,Other,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
15,approx_years_lodging_to_decision,Timing,Decision year minus proceeding lodged year; ap...,YES / contemporaneous or historical
16,procedures,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
17,n_procedures,Other,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
18,outcomes,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
19,n_outcomes,Other,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
20,procedure__action_for_annulment_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
21,procedure__action_for_damages_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
22,procedure__action_for_failure_to_act_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
23,procedure__action_for_failure_to_fulfill_oblig...,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
24,procedure__appeal_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
25,procedure__application_as_to_costs_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
26,procedure__application_concerning_the_responsi...,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
27,procedure__application_for_interim_measures_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
28,procedure__application_for_interpretation_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
29,procedure__application_for_legal_aid_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
30,procedure__application_for_measures_of_inquiry...,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
31,procedure__application_for_revision_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
32,procedure__application_to_intervene_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
33,procedure__application_to_set_aside_a_judgment...,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
34,procedure__arbitration_clause_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
35,procedure__proceeding_after_a_referral_back_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
36,procedure__reference_for_a_preliminary_ruling_...,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
37,procedure__review_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
38,procedure__staff_case_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical
39,outcome__inadmissible_count,Procedure / case structure,Constructed directly from the named IUROPA fie...,YES / contemporaneous or historical

In [20]:
# ============================================================
# 16. EXPORT: node_features.xlsx
# ============================================================

# Excel's cell-string limit is handled above. Datetime columns are written as real dates.
with pd.ExcelWriter(OUTPUT_XLSX, engine="openpyxl", datetime_format="yyyy-mm-dd", date_format="yyyy-mm-dd") as writer:
    nodes.to_excel(writer, sheet_name="nodes", index=False)
    feature_dictionary.to_excel(writer, sheet_name="feature_dictionary", index=False)
    missingness.to_excel(writer, sheet_name="missingness", index=False)

# Light workbook formatting for inspection.
from openpyxl import load_workbook

wb = load_workbook(OUTPUT_XLSX)
for ws in wb.worksheets:
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    # Keep widths readable without scanning every cell in a very large workbook.
    for col_cells in list(ws.columns)[:40]:
        letter = col_cells[0].column_letter
        sample = [str(cell.value) if cell.value is not None else "" for cell in col_cells[:200]]
        width = min(max([len(x) for x in sample] + [10]) + 2, 45)
        ws.column_dimensions[letter].width = width

wb.save(OUTPUT_XLSX)

print(f"Saved: {OUTPUT_XLSX.resolve()}")
print(f"Rows: {len(nodes):,}")
print(f"Features: {nodes.shape[1]:,}")

Saved: C:\Users\laze\Downloads\IUROPA\IUROPA\node_features.xlsx
Rows: 25,778
Features: 271