In [1]:
import os

os.listdir(".")

['.ipynb_checkpoints',
 'advocate_general_assignments.csv',
 'appeals.csv',
 'appointments.csv',
 'biographies.csv',
 'cases.csv',
 'chamber_assignments.csv',
 'citations.csv',
 'codebook.pdf',
 'decisions.csv',
 'decisions_curated.csv',
 'directory_codes.csv',
 'free_movement.csv',
 'headnotes.csv',
 'hearings.csv',
 'issues.csv',
 'joins.csv',
 'judges_advocates_general.csv',
 'judge_advocate_general_careers_curated.csv',
 'judge_assignments.csv',
 'keywords.csv',
 'lawyers.csv',
 'national_courts.csv',
 'observers.csv',
 'parties.csv',
 'parties_lawyers_curated.csv',
 'positions.csv',
 'positions_by_actor.csv',
 'procedures.csv',
 'proceedings.csv',
 'proceedings_curated.csv',
 'proceeding_suffixes.csv',
 'referrals.csv',
 'transfers.csv',
 'Untitled.ipynb']

In [2]:
import pandas as pd
from pathlib import Path
from IPython.display import display

# Find all CSV files in the current folder
csv_files = sorted(Path(".").glob("*.csv"))

# Store DataFrames here
dfs = {}

for file in csv_files:
    name = file.stem  # e.g. "cases.csv" -> "cases"
    
    try:
        dfs[name] = pd.read_csv(file)
        
        print("=" * 100)
        print(f"{file.name} | shape: {dfs[name].shape}")
        print("=" * 100)
        
        display(dfs[name].head())
        
    except Exception as e:
        print(f"Could not read {file.name}: {e}")

====================================================================================================
advocate_general_assignments.csv | shape: (15357, 2)
====================================================================================================

                      decision_id              advocate_general_id
0  DOC_JUDG_CJ_1954_0001_19541221  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
1  DOC_JUDG_CJ_1954_0002_19541221  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
2  DOC_JUDG_CJ_1954_0003_19550211  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
3  DOC_JUDG_CJ_1954_0004_19550211  ACT_EU_INST_CJEU_JUDG_AG_FR_LAG
4  DOC_JUDG_CJ_1954_0006_19550321  ACT_EU_INST_CJEU_JUDG_AG_DE_ROE

====================================================================================================
appeals.csv | shape: (4080, 2)
====================================================================================================

  original_proceeding_id appeal_proceeding_id
0      PROC_GC_1989_0038  PROC_CJ_1990_0107_P
1      PROC_GC_1989_0040  PROC_CJ_1990_0115_P
2      PROC_GC_1989_0072  PROC_CJ_1990_0126_P
3      PROC_GC_1989_0041  PROC_CJ_1990_0132_P
4      PROC_GC_1989_0034  PROC_CJ_1990_0145_P

====================================================================================================
appointments.csv | shape: (342, 7)
====================================================================================================

,actor_id,index,court,position,is_current,start_date,end_date
0,ACT_EU_INST_CJEU_JUDG_AG_BE_RAE,1,Civil Service Tribunal,judge,False,2005-10-06,2016-08-31
1,ACT_EU_INST_CJEU_JUDG_AG_DE_KRE,1,Civil Service Tribunal,judge,False,2005-10-06,2016-04-13
2,ACT_EU_INST_CJEU_JUDG_AG_EL_TAG,1,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06
3,ACT_EU_INST_CJEU_JUDG_AG_FI_KAN,1,Civil Service Tribunal,judge,False,2005-10-06,2009-10-06
4,ACT_EU_INST_CJEU_JUDG_AG_FR_GER,1,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06

====================================================================================================
biographies.csv | shape: (3869, 7)
====================================================================================================

,actor_id,index,entry_type,description,position_type,start_year,end_year
0,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,1,position,"Titular Professor of Labour Law at Urbino, Bol...",academic,NaN,NaN
1,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,2,position,Titular Professor of Comparative Private Law a...,academic,NaN,NaN
2,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,3,membership,Member of the High Council of the Judiciary,NaN,1976.0,1981.0
3,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,4,position,Advocate General at the Court of Justice,lawyer,1982.0,1988.0
4,ACT_EU_INST_CJEU_JUDG_AG_IT_MAN,5,position,Judge at the Court of Justice,judge,1988.0,1999.0

====================================================================================================
cases.csv | shape: (49467, 5)
====================================================================================================

             case_id case_number             court prefix  year
0  CASE_CJ_1953_0001      C-1/53  Court of Justice     C-  1953
1  CASE_CJ_1953_0002      C-2/53  Court of Justice     C-  1953
2  CASE_CJ_1953_0003      C-3/53  Court of Justice     C-  1953
3  CASE_CJ_1953_0004      C-4/53  Court of Justice     C-  1953
4  CASE_CJ_1954_0001      C-1/54  Court of Justice     C-  1954

====================================================================================================
chamber_assignments.csv | shape: (25736, 3)
====================================================================================================

                      decision_id             court     chamber
0  DOC_JUDG_CJ_1954_0001_19541221  Court of Justice  Full Court
1  DOC_JUDG_CJ_1954_0002_19541221  Court of Justice  Full Court
2  DOC_JUDG_CJ_1954_0003_19550211  Court of Justice  Full Court
3  DOC_JUDG_CJ_1954_0004_19550211  Court of Justice  Full Court
4  DOC_JUDG_CJ_1954_0006_19550321  Court of Justice  Full Court

====================================================================================================
citations.csv | shape: (283994, 2)
====================================================================================================

                 citing_decision_id                 cited_decision_id
0  DOC_JUDG_CJ_1998_0082_P_20000525  DOC_JUDG_CJ_1995_0008_P_19980528
1  DOC_JUDG_CJ_1998_0082_P_20000525    DOC_JUDG_CJ_1983_0264_19850704
2    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2017_0308_20181115
3    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2016_0249_20170615
4    DOC_JUDG_CJ_2018_0025_20190508    DOC_JUDG_CJ_2016_0560_20180307

====================================================================================================
decisions.csv | shape: (56951, 7)
====================================================================================================

,decision_id,decision_date,decision_type,court,lead_proceeding_id,ecli,celex
0,DEC_AG_VIEW_CJ_2004_0027_20040519,2004-05-19,AG view,Court of Justice,PROC_CJ_2004_0027,ECLI:EU:C:2004:313,62004CP0027
1,DEC_AG_VIEW_CJ_2008_0066_20080428,2008-04-28,AG view,Court of Justice,PROC_CJ_2008_0066,ECLI:EU:C:2008:253,62008CP0066
2,DEC_AG_VIEW_CJ_2008_0127_20080611,2008-06-11,AG view,Court of Justice,PROC_CJ_2008_0127,ECLI:EU:C:2008:335,62008CP0127
3,DEC_AG_VIEW_CJ_2008_0195_PPU_20080701,2008-07-01,AG view,Court of Justice,PROC_CJ_2008_0195_PPU,ECLI:EU:C:2008:377,62008CP0195
4,DEC_AG_VIEW_CJ_2008_0296_PPU_20080806,2008-08-06,AG view,Court of Justice,PROC_CJ_2008_0296_PPU,ECLI:EU:C:2008:455,62008CP0296

====================================================================================================
decisions_curated.csv | shape: (56951, 12)
====================================================================================================

,decision_id,ecli,celex,decision_type,decision_date,court,case_id,case_number,proceeding_id,proceeding_number,proceeding_suffix,proceeding_name
0,DEC_AG_VIEW_CJ_2004_0027_20040519,ECLI:EU:C:2004:313,62004CP0027,AG view,2004-05-19,Court of Justice,CASE_CJ_2004_0027,C-27/04,PROC_CJ_2004_0027,C-27/04,NaN,Commission of the European Communities v Counc...
1,DEC_AG_VIEW_CJ_2008_0066_20080428,ECLI:EU:C:2008:253,62008CP0066,AG view,2008-04-28,Court of Justice,CASE_CJ_2008_0066,C-66/08,PROC_CJ_2008_0066,C-66/08,NaN,Kozłowski
2,DEC_AG_VIEW_CJ_2008_0127_20080611,ECLI:EU:C:2008:335,62008CP0127,AG view,2008-06-11,Court of Justice,CASE_CJ_2008_0127,C-127/08,PROC_CJ_2008_0127,C-127/08,NaN,Blaise Baheten Metock and Others v Minister fo...
3,DEC_AG_VIEW_CJ_2008_0195_PPU_20080701,ECLI:EU:C:2008:377,62008CP0195,AG view,2008-07-01,Court of Justice,CASE_CJ_2008_0195,C-195/08,PROC_CJ_2008_0195_PPU,C-195/08 PPU,PPU,Inga Rinau
4,DEC_AG_VIEW_CJ_2008_0296_PPU_20080806,ECLI:EU:C:2008:455,62008CP0296,AG view,2008-08-06,Court of Justice,CASE_CJ_2008_0296,C-296/08,PROC_CJ_2008_0296_PPU,C-296/08 PPU,PPU,Ignacio Pedro Santesteban Goicoechea

====================================================================================================
directory_codes.csv | shape: (51955, 8)
====================================================================================================

,decision_id,code,section_code,section_label,major_code,major_label,minor_code,minor_label
0,DOC_JUDG_CJ_1954_0001_19541221,C-04.02,C,European Coal and Steel Community,C-04,Legal proceedings,C-04.02,Actions for annulment
1,DOC_JUDG_CJ_1954_0001_19541221,C-08.02,C,European Coal and Steel Community,C-08,Prices,C-08.02,Publication of prices
2,DOC_JUDG_CJ_1954_0002_19541221,C-04.02,C,European Coal and Steel Community,C-04,Legal proceedings,C-04.02,Actions for annulment
3,DOC_JUDG_CJ_1954_0002_19541221,C-08.02,C,European Coal and Steel Community,C-08,Prices,C-08.02,Publication of prices
4,DOC_JUDG_CJ_1954_0002_19541221,C-14,C,European Coal and Steel Community,C-14,General and final provisions,NaN,NaN

====================================================================================================
free_movement.csv | shape: (3454, 30)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,goods,services,persons,applicant_legal_person,applicant_economically_active,...,proportionality_test,discrimination_or_restriction,measure_rejected,protection_individual,measure_proportionate_outcome,derived_rights,incompatibility_eu_measure_primary,incompatibility_eu_measure_secondary,incompatibility_national_measure_primary,incompatibility_national_measure_secondary
0,1,DEC_C_1960_0009_J_19610714,ECLI:EU:C:1961:18:19610714,ECLI:EU:C:1961:18,61960CJ0009,1,NaN,0,1.0,NaN,...,0,0.0,-1,NaN,-1,NaN,0.0,0.0,0.0,0.0
1,2,DEC_C_1961_0007_J_19611219,ECLI:EU:C:1961:31:19611219,ECLI:EU:C:1961:31,61961CJ0007,1,NaN,0,0.0,NaN,...,0,0.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
2,3,DEC_C_1961_0010_J_19620227,ECLI:EU:C:1962:2:19620227,ECLI:EU:C:1962:2,61961CJ0010,1,NaN,0,0.0,NaN,...,0,0.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
3,4,DEC_C_1962_0002_J_19621214,ECLI:EU:C:1962:45:19621214,ECLI:EU:C:1962:45,61962CJ0002,1,NaN,0,0.0,NaN,...,0,1.0,1,NaN,-1,NaN,0.0,0.0,1.0,0.0
4,5,DEC_C_1962_0016_J_19621214,ECLI:EU:C:1962:47:19621214,ECLI:EU:C:1962:47,61962CJ0016,1,NaN,0,1.0,NaN,...,0,0.0,-1,NaN,-1,NaN,0.0,0.0,0.0,0.0

====================================================================================================
headnotes.csv | shape: (118753, 2)
====================================================================================================

,decision_id,headnote
0,DOC_JUDG_CJ_2007_0004_20240704,Remuneration not forming part of a taxable tra...
1,DOC_JUDG_CJ_2007_0004_20240704,Supply of services for consideration
2,DOC_JUDG_CJ_2007_0004_20240704,Taxable transactions
3,DOC_JUDG_CJ_2007_0004_20240704,Directive 2006/112/EC
4,DOC_JUDG_CJ_2007_0004_20240704,Value added tax (VAT)

====================================================================================================
hearings.csv | shape: (22215, 2)
====================================================================================================

                      decision_id hearing_date
0  DOC_JUDG_CJ_1969_0040_19700218   1970-01-29
1  DOC_JUDG_CJ_1969_0040_19700218   1970-01-15
2  DOC_JUDG_CJ_1969_0047_19700625   1970-04-21
3  DOC_JUDG_CJ_1969_0047_19700625   1970-03-10
4  DOC_JUDG_CJ_1971_0038_19720126   1971-11-23

====================================================================================================
issues.csv | shape: (5333, 17)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,legal_issue_order,is_split,is_merged,about_derogation,about_direct_effect,about_validity,list_legal_acts,national_law_primary,national_law_secondary,list_claiming_inadmissibility
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,0,0,no,no,no,directive,none,none,none
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,2,Should any importance be attached to the fact ...,2,0,0,no,no,no,directive,none,none,none
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,3,"a) Is it significant, as far as the applicatio...",3a_b_c,0,1,no,no,no,directive,none,none,none
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,4,Is the wording used in Article 13B(d) points 3...,4,0,0,no,no,no,directive,none,none,none
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,5,"In interpreting Article 13B(d) points 3 to 5, ...",5,0,0,no,no,no,directive,none,none,none

====================================================================================================
joins.csv | shape: (6882, 2)
====================================================================================================

  joined_proceeding_id lead_proceeding_id
0    PROC_CJ_1954_0009  PROC_CJ_1954_0007
1    PROC_CJ_1954_0010  PROC_CJ_1954_0008
2    PROC_CJ_1957_0003  PROC_CJ_1956_0007
3    PROC_CJ_1957_0004  PROC_CJ_1956_0007
4    PROC_CJ_1957_0005  PROC_CJ_1956_0007

====================================================================================================
judge_advocate_general_careers_curated.csv | shape: (342, 19)
====================================================================================================

,actor_id,display_label,display_label_ascii,full_name,first_name,last_name,member_state,birth_year,is_female,court,position,is_current,start_date,end_date,was_judge,was_academic,was_civil_servant,was_lawyer,was_politician
0,ACT_EU_INST_CJEU_JUDG_AG_BE_RAE,Van Raepenbusch,Van Raepenbusch,Sean Van Raepenbusch,Sean,Van Raepenbusch,Belgium,1956,0,Civil Service Tribunal,judge,False,2005-10-06,2016-08-31,0,1,1,1,0
1,ACT_EU_INST_CJEU_JUDG_AG_DE_KRE,Kreppel,Kreppel,Horstpeter Kreppel,Horstpeter,Kreppel,Germany,1945,0,Civil Service Tribunal,judge,False,2005-10-06,2016-04-13,1,1,1,1,0
2,ACT_EU_INST_CJEU_JUDG_AG_EL_TAG,Tagaras,Tagaras,Haris Tagaras,Haris,Tagaras,Greece,1955,0,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06,0,1,1,1,0
3,ACT_EU_INST_CJEU_JUDG_AG_FI_KAN,Kanninen,Kanninen,Heikki Kanninen,Heikki,Kanninen,Finland,1952,0,Civil Service Tribunal,judge,False,2005-10-06,2009-10-06,1,1,1,1,0
4,ACT_EU_INST_CJEU_JUDG_AG_FR_GER,Gervasoni,Gervasoni,Stéphane Gervasoni,Stéphane,Gervasoni,France,1967,0,Civil Service Tribunal,judge,False,2005-10-06,2011-10-06,1,1,1,1,0

====================================================================================================
judge_assignments.csv | shape: (119036, 3)
====================================================================================================

,decision_id,judge_id,is_judge_rapporteur
0,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_BE_DEL,False
1,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_DE_RIE,True
2,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_FR_REU,False
3,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_IT_PIL,False
4,DOC_JUDG_CJ_1954_0001_19541221,ACT_EU_INST_CJEU_JUDG_AG_LU_HAM,False

====================================================================================================
judges_advocates_general.csv | shape: (278, 9)
====================================================================================================

,actor_id,display_label,display_label_ascii,full_name,first_name,last_name,member_state,birth_year,is_female
0,ACT_EU_INST_CJEU_JUDG_AG_DE_ALB,Alber,Alber,Siegbert Alber,Siegbert,Alber,Germany,1936,0
1,ACT_EU_INST_CJEU_JUDG_AG_BG_ARA,Arabadjiev,Arabadjiev,Alexander Arabadjiev,Alexander,Arabadjiev,Bulgaria,1949,0
2,ACT_EU_INST_CJEU_JUDG_AG_ES_ARA_SAH,Arastey Sahún,Arastey Sahun,Maria Lourdes Arastey Sahún,Maria Lourdes,Arastey Sahún,Spain,1959,1
3,ACT_EU_INST_CJEU_JUDG_AG_CY_ARE,Arestis,Arestis,George Arestis,George,Arestis,Cyprus,1945,0
4,ACT_EU_INST_CJEU_JUDG_AG_AT_AZI,Azizi,Azizi,Josef Azizi,Josef,Azizi,Austria,1948,0

====================================================================================================
keywords.csv | shape: (58859, 2)
====================================================================================================

                      decision_id       keyword
0  DOC_JUDG_CJ_1954_0001_19541221  ECSC matters
1  DOC_JUDG_CJ_1954_0001_19541221        Prices
2  DOC_JUDG_CJ_1954_0002_19541221  ECSC matters
3  DOC_JUDG_CJ_1954_0002_19541221        Prices
4  DOC_JUDG_CJ_1954_0003_19550211  ECSC matters

====================================================================================================
lawyers.csv | shape: (217008, 6)
====================================================================================================

,decision_id,index,lawyer_id,lawyer_name,client_id,client_name
0,DOC_JUDG_CJ_1954_0001_19541221,1,ACT_LAW_[reuter],Reuter,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE
1,DOC_JUDG_CJ_1954_0001_19541221,3,ACT_LAW_[coutard],Coutard,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
2,DOC_JUDG_CJ_1954_0001_19541221,2,ACT_LAW_[gaudet],Gaudet,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
3,DOC_JUDG_CJ_1954_0002_19541221,4,ACT_LAW_[coutard],Coutard,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...
4,DOC_JUDG_CJ_1954_0002_19541221,3,ACT_LAW_[catalano],Catalano,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...

====================================================================================================
national_courts.csv | shape: (1566, 13)
====================================================================================================

,key_id,iuropa_national_court_id,national_court,iuropa_member_state_id,member_state,court_location,english_translation,in_hierarchy,court_level,court_prestige,court_collegiality,court_competence,court_competence_detailed
0,1,NAT_COURT_AT_ASW,Arbeits- und Sozialgericht Wien,ACT_EU_MS_AT,Austria,Vienna,Labor and Social Court,1,lower court,not applicable,panel,specialized,labor law; social law
1,2,NAT_COURT_AT_A,Asylgerichtshof,ACT_EU_MS_AT,Austria,Vienna,Asylum Court,1,higher court,not applicable,panel,specialized,immigration law
2,3,NAT_COURT_AT_BS_1_REG_LIN_FD_OBE,Berufungssenat I der Region Linz bei der Finan...,ACT_EU_MS_AT,Austria,Linz,Appeals Senate I of the Linz Region at the Sta...,0,not applicable,lower court,panel,specialized,tax law
3,4,NAT_COURT_AT_BS_5_FD_WIE_NIE_BUR,Berufungssenat V der Finanzlandesdirektion für...,ACT_EU_MS_AT,Austria,Vienna,Appeals Senate V of the State Financial Direct...,0,not applicable,lower court,panel,specialized,tax law
4,5,NAT_COURT_AT_BG_BLE,Bezirksgericht Bleiburg,ACT_EU_MS_AT,Austria,Bleiburg,District Court of Bleiburg,1,lower court,not applicable,single judge,general,not applicable

====================================================================================================
observers.csv | shape: (38783, 5)
====================================================================================================

,decision_id,index,observer_id,observer_name,observer_type
0,DOC_JUDG_CJ_1962_0028_19630327,1,ACT_COMP_[societe-da-costa-en-schaake-n-v],société Da Costa en Schaake N. V.,company
1,DOC_JUDG_CJ_1962_0028_19630327,2,ACT_COMP_[societe-jacob-meijer-n-v],société Jacob Meijer N. V.,company
2,DOC_JUDG_CJ_1962_0028_19630327,3,ACT_COMP_[societe-hoechst-holland-n-v],société Hoechst-Holland N. V.,company
3,DOC_JUDG_CJ_1962_0028_19630327,4,ACT_NAT_INST_[administration-fiscale-neerlanda...,administration fiscale néerlandaise,national institution
4,DOC_JUDG_CJ_1963_0073_19640218,1,ACT_COMP_[n-v-internationale-crediet-en-handel...,N. V. Internationale Crediet-en Handelsverenig...,company

====================================================================================================
parties.csv | shape: (129629, 6)
====================================================================================================

,decision_id,index,party_id,party_name,party_type,party_role
0,DOC_JUDG_CJ_1954_0001_19541221,1,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE,EU member state,applicant
1,DOC_JUDG_CJ_1954_0001_19541221,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant
2,DOC_JUDG_CJ_1954_0002_19541221,1,ACT_EU_MS_IT,GOUVERNEMENT DE LA RÉPUBLIQUE ITALIENNE,EU member state,applicant
3,DOC_JUDG_CJ_1954_0002_19541221,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant
4,DOC_JUDG_CJ_1954_0003_19550211,1,ACT_ORG_[associazione-industrie-siderurgiche-i...,ASSOCIAZIONE INDUSTRIE SIDERURGICHE ITALIANE,organization,applicant

====================================================================================================
parties_lawyers_curated.csv | shape: (129629, 12)
====================================================================================================

,decision_id,decision_date,court,proceeding_id,proceeding_name,party_index,party_id,party_name,party_type,party_role,lawyer_count,lawyer_name_list
0,DOC_JUDG_CJ_1954_0001_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0001,France v ECSC High Authority,1,ACT_EU_MS_FR,GOUVERNEMENT DE LA RÉPUBLIQUE FRANÇAISE,EU member state,applicant,1,Reuter
1,DOC_JUDG_CJ_1954_0001_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0001,France v ECSC High Authority,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant,2,Coutard; Gaudet
2,DOC_JUDG_CJ_1954_0002_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0002,Italian Republic v High Authority of the Europ...,1,ACT_EU_MS_IT,GOUVERNEMENT DE LA RÉPUBLIQUE ITALIENNE,EU member state,applicant,2,Arias; Monaco
3,DOC_JUDG_CJ_1954_0002_19541221,1954-12-21,Court of Justice,PROC_CJ_1954_0002,Italian Republic v High Authority of the Europ...,2,ACT_EU_INST_COM,HAUTE AUTORITÉ DE LA COMMUNAUTÉ EUROPÉENNE DU ...,EU institution,defendant,2,Coutard; Catalano
4,DOC_JUDG_CJ_1954_0003_19550211,1955-02-11,Court of Justice,PROC_CJ_1954_0003,Assider v ECSC High Authority,1,ACT_ORG_[associazione-industrie-siderurgiche-i...,ASSOCIAZIONE INDUSTRIE SIDERURGICHE ITALIANE,organization,applicant,2,Grassetti; Rebua

====================================================================================================
positions.csv | shape: (18617, 14)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,position_id,position,for_national_court,national_autonomy,individual_rights,list_actors_primary,list_actors_secondary
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,Yes and no,no,would restrict autonomy,not applicable,Advocate General; applicant; Court of Justice ...,none
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,2,No and no,no,would not restrict autonomy,not applicable,defendant,none
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,3,No,no,would not restrict autonomy,not applicable,European Commission,none
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,4,some of the operations are covered by the exem...,no,competing effect on autonomy,not applicable,United Kingdom,none
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,2,Should any importance be attached to the fact ...,5,Yes,no,uncertain,not applicable,applicant,none

====================================================================================================
positions_by_actor.csv | shape: (41595, 15)
====================================================================================================

,key_id,iuropa_decision_id,cjeu_decision_id,ecli,celex,legal_issue_id,legal_issue,position_id,position_type,position,for_national_court,national_autonomy,individual_rights,iuropa_actor_id,actor
0,1,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,none,Advocate General
1,2,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,none,applicant
2,3,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,1,primary,Yes and no,no,would restrict autonomy,not applicable,ACT_EU_INST_CJEU,Court of Justice of the European Union (CJEU)
3,4,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,2,primary,No and no,no,would not restrict autonomy,not applicable,none,defendant
4,5,DEC_C_1995_0002_J_19970605,ECLI:EU:C:1997:278:19970605,ECLI:EU:C:1997:278,61995CJ0002,1,Does Article 13B(d) points 3 to 5 of the Sixth...,3,primary,No,no,would not restrict autonomy,not applicable,ACT_EU_INST_COM,European Commission

====================================================================================================
procedures.csv | shape: (30261, 4)
====================================================================================================

                      decision_id  index             procedure     outcome
0  DOC_JUDG_CJ_1954_0001_19541221      1  action for annulment   unfounded
1  DOC_JUDG_CJ_1954_0001_19541221      2  action for annulment  successful
2  DOC_JUDG_CJ_1954_0002_19541221      1  action for annulment   unfounded
3  DOC_JUDG_CJ_1954_0002_19541221      2  action for annulment  successful
4  DOC_JUDG_CJ_1954_0003_19550211      1  action for annulment   unfounded

====================================================================================================
proceeding_suffixes.csv | shape: (59, 2)
====================================================================================================

  proceeding_suffix                                        description
0                AJ                       an application for legal aid
1            AJ-REC  an application for the rectification of a deci...
2            AJ-REV  an application for the revision of a decision ...
3               DEP                         an application as to costs
4              DISS  an application for the separation of joined cases

====================================================================================================
proceedings.csv | shape: (52785, 8)
====================================================================================================

,proceeding_id,case_id,proceeding_number,court,prefix,year,suffix,proceeding_name
0,PROC_CJ_1953_0001,CASE_CJ_1953_0001,C-1/53,Court of Justice,C-,1953,NaN,Verband Deutscher Reeder v ECSC High Authority
1,PROC_CJ_1953_0002,CASE_CJ_1953_0002,C-2/53,Court of Justice,C-,1953,NaN,Bunkerfirmen-Vereinigung v ECSC High Authority
2,PROC_CJ_1953_0003,CASE_CJ_1953_0003,C-3/53,Court of Justice,C-,1953,NaN,France v ECSC High Authority
3,PROC_CJ_1953_0004,CASE_CJ_1953_0004,C-4/53,Court of Justice,C-,1953,NaN,Belgium v ECSC High Authority
4,PROC_CJ_1954_0001,CASE_CJ_1954_0001,C-1/54,Court of Justice,C-,1954,NaN,France v ECSC High Authority

====================================================================================================
proceedings_curated.csv | shape: (52785, 20)
====================================================================================================

,proceeding_id,case_id,court,year,proceeding_suffix,proceeding_name,is_main_proceeding,joined_proceeding_count,joined_proceeding_list,lead_proceeding_id,is_transferred,transferred_to_proceeding_id,appeal_count,appeal_list,is_appeal_of,appeal_of_list,decision_count,decision_list,has_judgment,has_ag_opinion
0,PROC_CJ_1953_0001,CASE_CJ_1953_0001,Court of Justice,1953,NaN,Verband Deutscher Reeder v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0001_19540507,0,0
1,PROC_CJ_1953_0002,CASE_CJ_1953_0002,Court of Justice,1953,NaN,Bunkerfirmen-Vereinigung v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0002_19540507,0,0
2,PROC_CJ_1953_0003,CASE_CJ_1953_0003,Court of Justice,1953,NaN,France v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0003_19531105,0,0
3,PROC_CJ_1953_0004,CASE_CJ_1953_0004,Court of Justice,1953,NaN,Belgium v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,1,DOC_ORD_CJ_1953_0004_19531030,0,0
4,PROC_CJ_1954_0001,CASE_CJ_1954_0001,Court of Justice,1954,NaN,France v ECSC High Authority,1,0,NaN,NaN,0,NaN,0,NaN,0,NaN,2,DOC_JUDG_CJ_1954_0001_19541221; DOC_OPIN_CJ_19...,1,1

====================================================================================================
referrals.csv | shape: (9269, 7)
====================================================================================================

,decision_id,index,national_court_id,national_court_name,member_state,date_referred,date_received
0,DOC_JUDG_CJ_1961_0013_19620406,1,ACT_NAT_CT_[cour-appel-haye-deuxieme-chambre],"cour d'appel de La Haye, deuxième chambre",Netherlands,1961-06-20,NaN
1,DOC_JUDG_CJ_1962_0026_19630205,1,ACT_NAT_CT_[tariefcommissie-tribunal-administr...,"Tariefcommissie, tribunal administratif néerla...",Netherlands,NaN,NaN
2,DOC_JUDG_CJ_1962_0028_19630327,1,ACT_NAT_CT_[tariefcommissie-tribunal-administr...,"Tariefcommissie, tribunal administratif néerla...",Netherlands,NaN,NaN
3,DOC_JUDG_CJ_1963_0073_19640218,1,ACT_NAT_CT_[tribunal-administratif-economique-...,Tribunal administratif économique de droit née...,Netherlands,NaN,NaN
4,DOC_JUDG_CJ_1963_0075_19640319,1,ACT_NAT_CT_[raad-van-beroep],Raad van Beroep,Netherlands,NaN,NaN

====================================================================================================
transfers.csv | shape: (894, 2)
====================================================================================================

  original_proceeding_id  new_proceeding_id
0      PROC_CJ_1986_0179  PROC_GC_1989_0001
1      PROC_CJ_1986_0186  PROC_GC_1989_0002
2      PROC_CJ_1986_0189  PROC_GC_1989_0003
3      PROC_CJ_1986_0192  PROC_GC_1989_0004
4      PROC_CJ_1986_0194  PROC_GC_1989_0005